In [1]:
# Load libraries
library("anndata")
library("DESeq2")
library("reticulate")

# Use the path to your Python executable in the virtual environment
use_python("/lila/home/forsythb/.virtualenvs/r-reticulate/bin/")

# Look at where Python is located
py_config()

# Import scanpy
sc <- import("scanpy")

Loading required package: S4Vectors

Warning message:
“package ‘S4Vectors’ was built under R version 4.3.2”
Loading required package: stats4

Loading required package: BiocGenerics

Warning message:
“package ‘BiocGenerics’ was built under R version 4.3.2”

Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Warning message:
“package ‘IRanges’ was built under R version 4.3.2”
Loading required package: GenomicRanges

Warning message:
“package ‘GenomicRanges’ was built under R version 4.3.2”
Loading required package: GenomeInfoDb

Warning message:
“package ‘GenomeInfoDb’ was built under R version 4.3.2”
Loading required package: SummarizedExperiment

Warning message:
“package ‘SummarizedExperiment’ was built under R version 4.3.2”
Loading required package: MatrixGenerics

Warning message:
“package ‘MatrixGenerics’ was built under R version 4.3.2”
Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Warning message:
“package ‘Biobase’ was built under R version 4.3.2”
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

python:         /lila/home/forsythb/.virtualenvs/r-reticulate/bin/python
libpython:      /home/forsythb/anaconda3/lib/libpython3.8.so
pythonhome:     /lila/home/forsythb/.virtualenvs/r-reticulate:/lila/home/forsythb/.virtualenvs/r-reticulate
version:        3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
numpy:          /lila/home/forsythb/.virtualenvs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.24.4

NOTE: Python version was forced by use_python() function

In [4]:
# Read in the adata
adata <- sc$read_h5ad("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output_new/metacells/metacells.020524/adata.post.combined.h5ad")

In [5]:
adata$obs

                                 Patient Tumor_Site Culture_Media
146_P_HISC_CTRL_1_SEACell-125    146     Primary    HISC
146_P_HISC_CTRL_1_SEACell-9      146     Primary    HISC
146_P_BASE_CTRL_1_SEACell-52     146     Primary    BASE
146_M_BASE_CTRL_1_SEACell-109    146     Metastatic BASE
146_P_Dediff_ZFPKD_1_SEACell-35  146     Primary    Dedifferentiated
146_P_Dediff_ZFPKD_2_SEACell-34  146     Primary    Dedifferentiated
146_P_Dediff_ZFPKD_2_SEACell-85  146     Primary    Dedifferentiated
146_M_BASE_CTRL_1_SEACell-115    146     Metastatic BASE
146_P_HISC_CTRL_1_SEACell-176    146     Primary    HISC
146_M_BASE_CTRL_1_SEACell-13     146     Metastatic BASE
146_P_BASE_CTRL_1_SEACell-241    146     Primary    BASE
146_M_HISC_ZFPKD_1_SEACell-81    146     Metastatic HISC
146_M_Dediff_CTRL_1_SEACell-92   146     Metastatic Dedifferentiated
146_P_BASE_ZFPKD_2_SEACell-118   146     Primary    BASE
146_M_HISC_CTRL_1_SEACell-70     146     Metastatic HISC
146_P_HISC_ZFPKD_1_SEACell-118   146     Primary    HISC
146_M_HISC_ZFPKD_1_SEACell-164   146     Metastatic HISC
146_P_HISC_CTRL_1_SEACell-130    146     Primary    HISC
146_M_Dediff_ZFPKD_1_SEACell-114 146     Metastatic Dedifferentiated
146_P_Dediff_ZFPKD_1_SEACell-166 146     Primary    Dedifferentiated
146_P_HISC_ZFPKD_1_SEACell-141   146     Primary    HISC
146_P_Dediff_ZFPKD_2_SEACell-140 146     Primary    Dedifferentiated
146_P_Dediff_ZFPKD_2_SEACell-17  146     Primary    Dedifferentiated
146_P_BASE_ZFPKD_2_SEACell-193   146     Primary    BASE
146_P_HISC_ZFPKD_2_SEACell-63    146     Primary    HISC
146_M_BASE_ZFPKD_1_SEACell-173   146     Metastatic BASE
146_P_HISC_ZFPKD_1_SEACell-184   146     Primary    HISC
146_P_HISC_ZFPKD_2_SEACell-201   146     Primary    HISC
146_P_Dediff_ZFPKD_2_SEACell-71  146     Primary    Dedifferentiated
146_P_HISC_CTRL_1_SEACell-2      146     Primary    HISC
⋮                                ⋮       ⋮          ⋮
146_M_HISC_CTRL_1_SEACell-139    146     Metastatic HISC
146_M_HISC_ZFPKD_1_SEACell-73    146     Metastatic HISC
146_M_Dediff_ZFPKD_2_SEACell-128 146     Metastatic Dedifferentiated
146_M_HISC_CTRL_1_SEACell-91     146     Metastatic HISC
146_P_HISC_CTRL_1_SEACell-135    146     Primary    HISC
146_P_BASE_ZFPKD_2_SEACell-28    146     Primary    BASE
146_M_BASE_ZFPKD_1_SEACell-37    146     Metastatic BASE
146_M_Dediff_ZFPKD_1_SEACell-15  146     Metastatic Dedifferentiated
146_M_Dediff_ZFPKD_2_SEACell-140 146     Metastatic Dedifferentiated
146_P_BASE_ZFPKD_2_SEACell-39    146     Primary    BASE
146_M_BASE_ZFPKD_1_SEACell-23    146     Metastatic BASE
146_P_Dediff_CTRL_1_SEACell-140  146     Primary    Dedifferentiated
146_P_BASE_ZFPKD_1_SEACell-113   146     Primary    BASE
146_P_HISC_ZFPKD_2_SEACell-114   146     Primary    HISC
146_P_Dediff_ZFPKD_1_SEACell-195 146     Primary    Dedifferentiated
146_P_Dediff_CTRL_1_SEACell-49   146     Primary    Dedifferentiated
146_M_HISC_ZFPKD_1_SEACell-168   146     Metastatic HISC
146_M_BASE_ZFPKD_2_SEACell-147   146     Metastatic BASE
146_P_Dediff_ZFPKD_2_SEACell-101 146     Primary    Dedifferentiated
146_M_BASE_CTRL_1_SEACell-87     146     Metastatic BASE
146_P_HISC_ZFPKD_1_SEACell-103   146     Primary    HISC
146_M_Dediff_ZFPKD_1_SEACell-27  146     Metastatic Dedifferentiated
146_M_Dediff_ZFPKD_1_SEACell-76  146     Metastatic Dedifferentiated
146_P_BASE_ZFPKD_2_SEACell-221   146     Primary    BASE
146_P_BASE_ZFPKD_2_SEACell-200   146     Primary    BASE
146_M_BASE_ZFPKD_2_SEACell-114   146     Metastatic BASE
146_P_Dediff_ZFPKD_2_SEACell-138 146     Primary    Dedifferentiated
146_P_BASE_CTRL_1_SEACell-125    146     Primary    BASE
146_P_Dediff_CTRL_1_SEACell-168  146     Primary    Dedifferentiated
146_M_Dediff_CTRL_1_SEACell-49   146     Metastatic Dedifferentiated
                                 ZFP_Expression Sample_Name          Batch
146_P_HISC_CTRL_1_SEACell-125    CTRL           146_P_HISC_CTRL_1    6
146_P_HISC_CTRL_1_SEACell-9      CTRL           146_P_HISC_CTRL_1    6
146_P_BASE_CTRL_1_SEACell-52     CTRL           146_P_BASE_CTRL_1    5
146_M_BASE_CTRL_1_SEACell-109    CTRL           146_M_BASE_CTRL_1    2
146_P_Dediff_ZFPKD_1_SEACell-35  ZFPKD          146_P_Dediff_ZFPKD_1 8
146_P_Dediff_ZFPKD_2_SEACell-34  ZFPKD          146_P_Dediff_ZFPKD_2 8
146_P_Dediff_ZFPKD_2_SEACell-85  ZFPKD          146_P_Dediff_ZFPKD_2 8
146_M_BASE_CTRL_1_SEACell-115    CTRL           146_M_BASE_CTRL_1    2
146_P_HISC_CTRL_1_SEACell-176    CTRL           146_P_HISC_CTRL_1    6
146_M_BASE_CTRL_1_SEACell-13     CTRL           146_M_BASE_CTRL_1    2
146_P_BASE_CTRL_1_SEACell-241    CTRL           146_P_BASE_CTRL_1    5
146_M_HISC_ZFPKD_1_SEACell-81    ZFPKD          146_M_HISC_ZFPKD_1   3
146_M_Dediff_CTRL_1_SEACell-92   CTRL           146_M_Dediff_CTRL_1  4
146_P_BASE_ZFPKD_2_SEACell-118   ZFPKD          146_P_BASE_ZFPKD_2   5
146_M_HISC_CTRL_1_SEACell-70     CTRL           146_M_HISC_CTRL_1    3
146_P_HISC_ZFPKD_1_SEACell-118   ZFPKD          146_P_HISC_ZFPKD_1   6
146_M_HISC_ZFPKD_1_SEACell-164   ZFPKD          146_M_HISC_ZFPKD_1   3
146_P_HISC_CTRL_1_SEACell-130    CTRL           146_P_HISC_CTRL_1    6
146_M_Dediff_ZFPKD_1_SEACell-114 ZFPKD          146_M_Dediff_ZFPKD_1 4
146_P_Dediff_ZFPKD_1_SEACell-166 ZFPKD          146_P_Dediff_ZFPKD_1 8
146_P_HISC_ZFPKD_1_SEACell-141   ZFPKD          146_P_HISC_ZFPKD_1   6
146_P_Dediff_ZFPKD_2_SEACell-140 ZFPKD          146_P_Dediff_ZFPKD_2 8
146_P_Dediff_ZFPKD_2_SEACell-17  ZFPKD          146_P_Dediff_ZFPKD_2 8
146_P_BASE_ZFPKD_2_SEACell-193   ZFPKD          146_P_BASE_ZFPKD_2   5
146_P_HISC_ZFPKD_2_SEACell-63    ZFPKD          146_P_HISC_ZFPKD_2   6
146_M_BASE_ZFPKD_1_SEACell-173   ZFPKD          146_M_BASE_ZFPKD_1   2
146_P_HISC_ZFPKD_1_SEACell-184   ZFPKD          146_P_HISC_ZFPKD_1   6
146_P_HISC_ZFPKD_2_SEACell-201   ZFPKD          146_P_HISC_ZFPKD_2   6
146_P_Dediff_ZFPKD_2_SEACell-71  ZFPKD          146_P_Dediff_ZFPKD_2 8
146_P_HISC_CTRL_1_SEACell-2      CTRL           146_P_HISC_CTRL_1    6
⋮                                ⋮              ⋮                    ⋮
146_M_HISC_CTRL_1_SEACell-139    CTRL           146_M_HISC_CTRL_1    3
146_M_HISC_ZFPKD_1_SEACell-73    ZFPKD          146_M_HISC_ZFPKD_1   3
146_M_Dediff_ZFPKD_2_SEACell-128 ZFPKD          146_M_Dediff_ZFPKD_2 4
146_M_HISC_CTRL_1_SEACell-91     CTRL           146_M_HISC_CTRL_1    3
146_P_HISC_CTRL_1_SEACell-135    CTRL           146_P_HISC_CTRL_1    6
146_P_BASE_ZFPKD_2_SEACell-28    ZFPKD          146_P_BASE_ZFPKD_2   5
146_M_BASE_ZFPKD_1_SEACell-37    ZFPKD          146_M_BASE_ZFPKD_1   2
146_M_Dediff_ZFPKD_1_SEACell-15  ZFPKD          146_M_Dediff_ZFPKD_1 4
146_M_Dediff_ZFPKD_2_SEACell-140 ZFPKD          146_M_Dediff_ZFPKD_2 4
146_P_BASE_ZFPKD_2_SEACell-39    ZFPKD          146_P_BASE_ZFPKD_2   5
146_M_BASE_ZFPKD_1_SEACell-23    ZFPKD          146_M_BASE_ZFPKD_1   2
146_P_Dediff_CTRL_1_SEACell-140  CTRL           146_P_Dediff_CTRL_1  8
146_P_BASE_ZFPKD_1_SEACell-113   ZFPKD          146_P_BASE_ZFPKD_1   5
146_P_HISC_ZFPKD_2_SEACell-114   ZFPKD          146_P_HISC_ZFPKD_2   6
146_P_Dediff_ZFPKD_1_SEACell-195 ZFPKD          146_P_Dediff_ZFPKD_1 8
146_P_Dediff_CTRL_1_SEACell-49   CTRL           146_P_Dediff_CTRL_1  8
146_M_HISC_ZFPKD_1_SEACell-168   ZFPKD          146_M_HISC_ZFPKD_1   3
146_M_BASE_ZFPKD_2_SEACell-147   ZFPKD          146_M_BASE_ZFPKD_2   2
146_P_Dediff_ZFPKD_2_SEACell-101 ZFPKD          146_P_Dediff_ZFPKD_2 8
146_M_BASE_CTRL_1_SEACell-87     CTRL           146_M_BASE_CTRL_1    2
146_P_HISC_ZFPKD_1_SEACell-103   ZFPKD          146_P_HISC_ZFPKD_1   6
146_M_Dediff_ZFPKD_1_SEACell-27  ZFPKD          146_M_Dediff_ZFPKD_1 4
146_M_Dediff_ZFPKD_1_SEACell-76  ZFPKD          146_M_Dediff_ZFPKD_1 4
146_P_BASE_ZFPKD_2_SEACell-221   ZFPKD          146_P_BASE_ZFPKD_2   5
146_P_BASE_ZFPKD_2_SEACell-200   ZFPKD          146_P_BASE_ZFPKD_2   5
146_M_BASE_ZFPKD_2_SEACell-114   ZFPKD          146_M_BASE_ZFPKD_2   2
146_P_Dediff_ZFPKD_2_SEACell-138 ZFPKD          146_P_Dediff_ZFPKD_2 8
146_P_BASE_CTRL_1_SEACell-125    CTRL           146_P_BASE_CTRL_1    5
146_P_Dediff_CTRL_1_SEACell-168  CTRL           146_P_Dediff_CTRL_1  8
146_M_Dediff_CTRL_1_SEACell-49   CTRL           146_M_Dediff_CTRL_1  4
                                 phenograph
146_P_HISC_CTRL_1_SEACell-125    15
146_P_HISC_CTRL_1_SEACell-9      0
146_P_BASE_CTRL_1_SEACell-52     1
146_M_BASE_CTRL_1_SEACell-109    2
146_P_Dediff_ZFPKD_1_SEACell-35  4
146_P_Dediff_ZFPKD_2_SEACell-34  8
146_P_Dediff_ZFPKD_2_SEACell-85  8
146_M_BASE_CTRL_1_SEACell-115    10
146_P_HISC_CTRL_1_SEACell-176    0
146_M_BASE_CTRL_1_SEACell-13     2
146_P_BASE_CTRL_1_SEACell-241    12
146_M_HISC_ZFPKD_1_SEACell-81    7
146_M_Dediff_CTRL_1_SEACell-92   14
146_P_BASE_ZFPKD_2_SEACell-118   12
146_M_HISC_CTRL_1_SEACell-70     7
146_P_HISC_ZFPKD_1_SEACell-118   0
146_M_HISC_ZFPKD_1_SEACell-164   2
146_P_HISC_CTRL_1_SEACell-130    0
146_M_Dediff_ZFPKD_1_SEACell-114 7
146_P_Dediff_ZFPKD_1_SEACell-166 4
146_P_HISC_ZFPKD_1_SEACell-141   0
146_P_Dediff_ZFPKD_2_SEACell-140 4
146_P_Dediff_ZFPKD_2_SEACell-17  8
146_P_BASE_ZFPKD_2_SEACell-193   6
146_P_HISC_ZFPKD_2_SEACell-63    15
146_M_BASE_ZFPKD_1_SEACell-173   2
146_P_HISC_ZFPKD_1_SEACell-184   0
146_P_HISC_ZFPKD_2_SEACell-201   0
146_P_Dediff_ZFPKD_2_SEACell-71  5
146_P_HISC_CTRL_1_SEACell-2      15
⋮                                ⋮
146_M_HISC_CTRL_1_SEACell-139    7
146_M_HISC_ZFPKD_1_SEACell-73    17
146_M_Dediff_ZFPKD_2_SEACell-128 13
146_M_HISC_CTRL_1_SEACell-91     7
146_P_HISC_CTRL_1_SEACell-135    0
146_P_BASE_ZFPKD_2_SEACell-28    9
146_M_BASE_ZFPKD_1_SEACell-37    2
146_M_Dediff_ZFPKD_1_SEACell-15  3
146_M_Dediff_ZFPKD_2_SEACell-140 17
146_P_BASE_ZFPKD_2_SEACell-39    6
146_M_BASE_ZFPKD_1_SEACell-23    12
146_P_Dediff_CTRL_1_SEACell-140  16
146_P_BASE_ZFPKD_1_SEACell-113   12
146_P_HISC_ZFPKD_2_SEACell-114   15
146_P_Dediff_ZFPKD_1_SEACell-195 4
146_P_Dediff_CTRL_1_SEACell-49   16
146_M_HISC_ZFPKD_1_SEACell-168   2
146_M_BASE_ZFPKD_2_SEACell-147   20
146_P_Dediff_ZFPKD_2_SEACell-101 4
146_M_BASE_CTRL_1_SEACell-87     10
146_P_HISC_ZFPKD_1_SEACell-103   0
146_M_Dediff_ZFPKD_1_SEACell-27  3
146_M_Dediff_ZFPKD_1_SEACell-76  3
146_P_BASE_ZFPKD_2_SEACell-221   12
146_P_BASE_ZFPKD_2_SEACell-200   1
146_M_BASE_ZFPKD_2_SEACell-114   20
146_P_Dediff_ZFPKD_2_SEACell-138 8
146_P_BASE_CTRL_1_SEACell-125    12
146_P_Dediff_CTRL_1_SEACell-168  16
146_M_Dediff_CTRL_1_SEACell-49   14

In [8]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [9]:
count_matrix

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [2,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [3,] 2    2    3    4    4    4    4    5    3    4     ⋯     0     3
 [4,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [5,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [6,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [7,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [8,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [9,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[10,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[12,] 0    2    2    0    2    0    1    3    2    0     ⋯     3     2
[13,] 4    2    3    2    3    3    3    3    3    0     ⋯     0     3
[14,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[19,] 2    2    0    0    0    0    0    0    0    0     ⋯     0     1
[20,] 4    2    3    2    1    2    1    2    2    0     ⋯     2     3
[21,] 1    2    2    3    0    0    0    3    3    0     ⋯     2     3
[22,] 0    2    3    0    1    2    2    1    1    0     ⋯     3     3
[23,] 0    3    3    0    3    3    3    2    1    3     ⋯     3     3
[24,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[25,] 0    1    1    0    0    2    1    0    1    0     ⋯     2     1
[26,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[27,] 3    3    2    0    3    3    3    1    1    0     ⋯     2     2
[28,] 2    1    1    0    1    0    1    0    0    0     ⋯     0     1
[29,] 2    2    2    0    1    0    0    2    3    0     ⋯     2     2
[30,] 1    1    2    0    1    3    2    2    1    0     ⋯     3     2
[31,] ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮     ⋱     ⋮     ⋮
[32,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     1
[33,] 1    1    1    0    0    1    1    0    1    0     ⋯     2     1
[34,] 0    1    1    0    0    2    1    1    0    3     ⋯     0     2
[35,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0
[36,] 1    1    0    0    0    2    1    0    0    0     ⋯     0     0
[37,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[38,] 0    1    1    2    0    1    1    3    1    0     ⋯     0     3
[39,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[40,] 0    0    1    0    1    0    1    1    0    0     ⋯     0     1
[41,] 0    0    1    0    1    0    0    0    0    0     ⋯     0     0
[42,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[43,] 0    1    1    0    1    2    1    0    0    3     ⋯     0     2
[44,] 2    0    0    0    1    2    1    1    0    0     ⋯     0     2
[45,] 5    3    3    4    3    3    4    4    4    4     ⋯     0     4
[46,] 5    3    3    3    4    4    4    5    4    3     ⋯     0     4
[47,] 0    1    2    0    1    2    1    0    1    0     ⋯     2     2
[48,] 0    0    0    0    1    1    1    3    0    0     ⋯     0     0
[49,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[50,] 1    1    2    2    1    1    1    1    2    0     ⋯     2     2
[51,] 1    1    2    0    1    2    1    1    1    0     ⋯     2     2
[52,] 0    1    2    0    1    0    2    0    2    0     ⋯     2     1
[53,] 3    1    3    0    0    1    0    0    3    0     ⋯     2     0
[54,] 0    4    4    0    5    3    0    0    4    0     ⋯     4     3
[55,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0
[56,] 0    0    0    0    0    0    1    0    1    0     ⋯     0     2
[57,] 3    2    3    2    3    4    2    3    3    0     ⋯     0     3
[58,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[59,] 3    1    3    0    1    3    3    2    2    3     ⋯     3     3
[60,] 0    2    1    2    1    0    1    1    1    3     ⋯     0     2
[61,] 2    1    1    3    2    2    2    1    1    3     ⋯     0     2
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0
 [2,] 0     0     0     0     0     0     0     0
 [3,] 3     4     4     3     4     4     3     3
 [4,] 0     0     0     0     0     0     0     0
 [5,] 0     0     0     0     0     0     0     0
 [6,] 0     0     0     0     1     0     0     1
 [7,] 0     0     0     0     0     0     0     0
 [8,] 0     0     0     0     0     0     0     0
 [9,] 0     0     0     0     0     0     1     0
[10,] 0     0     0     0     1     0     0     0
[11,] 0     0     0     0     0     0     0     0
[12,] 2     2     1     2     1     2     2     1
[13,] 3     4     3     3     3     3     3     3
[14,] 0     0     0     0     0     0     0     0
[15,] 0     0     0     0     0     0     0     0
[16,] 1     0     0     0     1     0     1     1
[17,] 0     0     0     0     0     0     0     0
[18,] 0     0     0     0     0     0     0     0
[19,] 1     0     0     1     0     0     1     2
[20,] 3     0     2     3     1     0     2     3
[21,] 2     3     2     2     2     2     2     2
[22,] 2     3     3     3     2     2     2     2
[23,] 3     2     3     3     3     2     3     3
[24,] 0     0     0     0     0     0     0     0
[25,] 0     2     2     2     1     0     2     1
[26,] 0     0     0     0     0     0     0     0
[27,] 3     2     2     3     3     2     3     2
[28,] 1     2     2     1     0     3     0     1
[29,] 2     2     2     3     1     2     2     3
[30,] 3     2     0     1     3     0     3     2
[31,] ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮
[32,] 1     0     0     1     1     0     0     1
[33,] 2     0     0     1     0     2     0     1
[34,] 1     0     0     1     3     2     1     1
[35,] 1     0     0     1     1     0     1     1
[36,] 2     0     1     2     1     2     2     2
[37,] 0     0     0     0     0     0     0     0
[38,] 2     3     1     3     1     2     1     2
[39,] 0     0     0     0     0     0     0     0
[40,] 1     0     2     1     1     0     1     0
[41,] 0     0     0     1     1     0     0     0
[42,] 0     0     0     0     0     0     0     0
[43,] 1     0     0     1     0     0     0     0
[44,] 1     0     0     0     1     0     1     1
[45,] 3     4     2     4     5     4     5     3
[46,] 3     5     2     3     5     4     4     3
[47,] 2     0     1     1     2     0     1     1
[48,] 1     0     1     0     2     2     1     1
[49,] 0     0     0     0     1     0     0     0
[50,] 2     2     0     2     1     2     1     0
[51,] 2     3     1     2     2     0     2     1
[52,] 2     2     2     1     1     3     1     1
[53,] 2     2     3     3     6     3     1     2
[54,] 4     0     4     4     2     2     2     2
[55,] 0     0     0     0     1     0     0     0
[56,] 1     0     0     0     1     0     0     0
[57,] 3     3     2     3     3     3     3     3
[58,] 1     0     0     0     0     0     0     0
[59,] 2     3     3     2     4     3     3     3
[60,] 1     0     0     2     0     0     1     3
[61,] 2     0     1     2     3     2     2     2

In [10]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression", "Batch")]

In [11]:
# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)
coldata$Batch <- factor(coldata$Batch)

In [12]:
# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + ZFP_Expression
)

converting counts to integer mode

In [13]:
# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

# Set the reference levels
coldata$Tumor_Site<-relevel(coldata$Tumor_Site,ref="Primary")
coldata$Culture_Media<-relevel(coldata$Culture_Media,ref="BASE")
coldata$ZFP_Expression<-relevel(coldata$ZFP_Expression,ref="CTRL")

# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + ZFP_Expression + ZFP_Expression:Culture_Media  
)

# Perform DESeq analysis
# dds_1 <- DESeq(dds_1)

# # Extract results
# result_names_1 <- resultsNames(dds_1)
# result_names_1

# # Specify the contrast and extract results
# res_1 <- results(dds_1)
# res_1

converting counts to integer mode

In [35]:
# Specify the date
date <- '020224'

# Specify the directory path
directory_path <- paste("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output_new/deseq/deseq.", date, sep="")

# Check if the directory exists, and create it if not
if (!dir.exists(directory_path)) {
  dir.create(directory_path, recursive = TRUE)
}

# Specify the file path where you want to save the results
result_file <- paste(directory_path, "/metacells_zfpexp_intcm_results.csv", sep="")

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = paste(directory_path, "/metacells_zfpexp_intcm_dds.rds", sep=""))

# Save the DESeq results
saveRDS(results(dds_1), file = paste(directory_path, "/metacells_zfpexp_intcm_results.rds", sep=""))

In [ ]:
res1 <- results(dds, contrast = c("Type", "1020A", "lactate"))

ddsLRT <- DESeq(dds, test="LRT", reduced= ~ CellType)
resLRT <- results(ddsLRT)

In [39]:
full_model <- ~ Tumor_Site + Culture_Media + ZFP_Expression + ZFP_Expression:Culture_Media
reduced_model <- ~ Tumor_Site + Culture_Media + ZFP_Expression

In [40]:
dds <- DESeqDataSetFromMatrix(countData = count_matrix, colData = coldata, design = ~ Tumor_Site + Culture_Media + ZFP_Expression + ZFP_Expression:Culture_Media)
dds_lrt <- DESeq(dds, test="LRT", reduced = ~ Tumor_Site + Culture_Media + ZFP_Expression)

converting counts to integer mode

estimating size factors

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

final dispersion estimates

fitting model and testing

-- replacing outliers and refitting for 18 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

estimating dispersions

fitting model and testing

In [41]:
# Specify the date
date <- '020224'

# Specify the directory path
directory_path <- paste("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output_new/deseq/deseq.", date, sep="")

# Check if the directory exists, and create it if not
if (!dir.exists(directory_path)) {
  dir.create(directory_path, recursive = TRUE)
}

# Specify the file path where you want to save the results
result_file <- paste(directory_path, "/metacells_zfpexp_intcm_lrt_results.csv", sep="")

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = paste(directory_path, "/metacells_zfpexp_intcm_lrt_dds.rds", sep=""))

# Save the DESeq results
saveRDS(results(dds_1), file = paste(directory_path, "/metacells_zfpexp_intcm_lrt_results.rds", sep=""))