In [3]:
# Load libraries
library("anndata")
library("DESeq2")
library("reticulate")

# Use the path to your Python executable in the virtual environment
use_python("/lila/home/forsythb/.virtualenvs/r-reticulate/bin/")

# Look at where Python is located
py_config()

# Import scanpy
sc <- import("scanpy")

python:         /lila/home/forsythb/.virtualenvs/r-reticulate/bin/python
libpython:      /home/forsythb/anaconda3/lib/libpython3.8.so
pythonhome:     /lila/home/forsythb/.virtualenvs/r-reticulate:/lila/home/forsythb/.virtualenvs/r-reticulate
version:        3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
numpy:          /lila/home/forsythb/.virtualenvs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.24.4

NOTE: Python version was forced by use_python() function

In [2]:
# Read in the adata
adata <- sc$read_h5ad('/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output_new/postprocess_adata/postprocess_adata.020624/adata.combined.postprocess.h5ad')

In [3]:
# Filter rows for primary tumor
primary_tumor <- adata[rownames(adata$obs) %in% '146P', ]
write.h5ad(primary_tumor, '/data/chanjlab/CRC_ZFP36L2.092023/Organoid/input/degs/primary_tumor.h5ad')

# Filter rows for metastatic tumor
metastatic_tumor <- adata[rownames(adata$obs) %in% 'KG146Li', ]
write.h5ad(metastatic_tumor, '/data/chanjlab/CRC_ZFP36L2.092023/Organoid/input/degs/metastatic_tumor.h5ad')

ERROR: Error in write.h5ad(primary_tumor, "/data/chanjlab/CRC_ZFP36L2.092023/Organoid/input/degs/primary_tumor.h5ad"): could not find function "write.h5ad"

In [3]:
adata$obs

                                                       background_fraction
KG146Li_BASE_shZFP36L2_4_GTCGAATTCGGACGTC-1            0.015236451
KG146Li_HISC_shCtrl_GGATCTAAGGTTATAG-1                 0.014875664
146P_dedifferentiation_shCtrl_CTCTCAGAGGTAGACC-1       0.045285905
146P_HISC_shZFP36L2_4_GTGCAGCAGAGAGGGC-1               0.045060653
146P_BASE_shZFP36L2_3_TAGAGTCAGAAAGTCT-1               0.021178186
146P_BASE_shCTRL_GGGTCACGTGATACTC-1                    0.016049281
KG146Li_BASE_shZFP36L2_4_TTGTTGTAGTCACTGT-1            0.016974458
146P_BASE_shCTRL_GGAGATGAGTTCCAGT-1                    0.030841348
146P_BASE_shZFP36L2_4_GAGTTTGCAAGACGGT-1               0.031681873
146P_BASE_shZFP36L2_3_CTAACCCTCACATCAG-1               0.009775235
146P_HISC_shCTRL_TGCAGATAGTCTACCA-1                    0.020285608
146P_dedifferentiation_shZFP36L2_3_CACTTCGCATGTGGTT-1  0.024672286
146P_HISC_shCTRL_AAGAACAAGGACACTG-1                    0.008848247
146P_HISC_shCTRL_GAATAGACAGGGATAC-1                    0.031017367
146P_BASE_shZFP36L2_3_CACTGGGTCGCAGTCG-1               0.098661154
146P_HISC_shZFP36L2_4_ACATCCCTCGCCACTT-1               0.012117408
KG146Li_BASE_shZFP36L2_4_AATTTCCCACTCCGAG-1            0.020287957
146P_dedifferentiation_shZFP36L2_4_GGTTCTCGTCTAACGT-1  0.070167407
146P_BASE_shZFP36L2_4_ATCATTCCAAGTGCTT-1               0.208653102
146P_dedifferentiation_shZFP36L2_3_CTCGAGGCACTTCCTG-1  0.214617128
KG146Li_HISC_shCtrl_ATTTCACGTTCGGTCG-1                 0.017082926
KG146Li_HISC_shCtrl_CCTCACAAGGCGTTAG-1                 0.008493069
146P_BASE_shZFP36L2_4_TCTACCGCAGCGGATA-1               0.028798290
KG146Li_HISC_shCtrl_GAATAGAAGCCACAAG-1                 0.019722937
146P_HISC_shCTRL_GCATGATGTGGCAACA-1                    0.094504566
KG146Li_BASE_shCtrl_GGAGGATTCGAAACAA-1                 0.084642459
146P_dedifferentiation_shZFP36L2_4_CACAGGCTCCCGGTAG-1  0.037096105
146Li_dedifferentiation_shZFP36L2_3_GATGAGGTCGCGAAGA-1 0.007708800
KG146Li_BASE_shCtrl_CCCTCAACATCGGTTA-1                 0.046056108
146P_BASE_shCTRL_GGGCTACCATCATCCC-1                    0.052338254
⋮                                                      ⋮
146P_BASE_shCTRL_TCGCACTCAGCGTAGA-1                    0.082924339
146P_dedifferentiation_shCtrl_GACCCAGTCAGCCTTC-1       0.207275593
146P_BASE_shZFP36L2_3_CTACCCATCGAGATGG-1               0.049064697
146P_BASE_shCTRL_CCTTCAGAGTATTCCG-1                    0.047858935
146P_dedifferentiation_shZFP36L2_4_TCCATCGAGTGGATTA-1  0.060108820
146P_dedifferentiation_shZFP36L2_4_TACGTCCAGTCACACT-1  0.092440290
146P_dedifferentiation_shZFP36L2_3_CACGTGGGTGTCTCCT-1  0.031784839
146P_dedifferentiation_shZFP36L2_4_CGTGCTTTCACGAACT-1  0.037501477
KG146Li_BASE_shZFP36L2_3_CATTCCGTCACAATGC-1            0.010666829
146Li_dedifferentiation_shZFP36L2_3_TTTCATGCATAACCCA-1 0.010304521
146P_HISC_shZFP36L2_4_GAGTGTTTCCTGTAAG-1               0.016772500
146P_BASE_shZFP36L2_3_TTCGGTCGTCCCAAAT-1               0.043182443
146P_dedifferentiation_shZFP36L2_3_ACTGCAACAGTGTACT-1  0.065017255
146P_dedifferentiation_shZFP36L2_4_TACCTCGTCGACTCCT-1  0.054367407
146P_BASE_shZFP36L2_4_AGGACGATCTCTCTTC-1               0.141145425
146P_dedifferentiation_shCtrl_AAGACTCGTGATATAG-1       0.058409733
146P_HISC_shZFP36L2_4_CCTCCTCCATATGGCT-1               0.072278003
KG146Li_BASE_shZFP36L2_3_TGAGGAGAGAGTCACG-1            0.011475674
KG146Li_HISC_shCtrl_GTAATGCGTATCAGCT-1                 0.009173697
KG146Li_BASE_shZFP36L2_3_GTGTTAGCATTACTCT-1            0.219628899
146P_HISC_shZFP36L2_4_ATGTCTTCAGTCCCGA-1               0.013453425
KG146Li_BASE_shCtrl_GTTTACTAGATGCTAA-1                 0.199460206
146P_BASE_shCTRL_CCTCAGTCAGGTATGG-1                    0.071603043
146Li_dedifferentiation_shZFP36L2_3_AGGTTGTCATAGAGGC-1 0.097381568
146Li_dedifferentiation_shCtrl_GTATTTCAGTGGCAGT-1      0.015853018
146P_HISC_shCTRL_CCTCACAGTTGGTGTT-1                    0.067409962
146P_BASE_shZFP36L2_3_TCACGCTTCATAGGCT-1               0.039564656
KG146Li_BASE_shZFP36L2_3_TTCTCTCCACCTGCGA-1            0.021414174
146P_dedifferentiation_shZFP36L2_4_TCGGGTGCAAACGGCA-1  0.086822847
146P_BASE_shZFP36L2_4_ACTGCAATCAGTGTTG-1               0.152413166
                                                       cell_probability
KG146Li_BASE_shZFP36L2_4_GTCGAATTCGGACGTC-1            0.9999540
KG146Li_HISC_shCtrl_GGATCTAAGGTTATAG-1                 0.9999546
146P_dedifferentiation_shCtrl_CTCTCAGAGGTAGACC-1       0.9999546
146P_HISC_shZFP36L2_4_GTGCAGCAGAGAGGGC-1               0.9999998
146P_BASE_shZFP36L2_3_TAGAGTCAGAAAGTCT-1               0.9999994
146P_BASE_shCTRL_GGGTCACGTGATACTC-1                    0.9999532
KG146Li_BASE_shZFP36L2_4_TTGTTGTAGTCACTGT-1            0.9999232
146P_BASE_shCTRL_GGAGATGAGTTCCAGT-1                    0.9999990
146P_BASE_shZFP36L2_4_GAGTTTGCAAGACGGT-1               0.9999999
146P_BASE_shZFP36L2_3_CTAACCCTCACATCAG-1               0.9999546
146P_HISC_shCTRL_TGCAGATAGTCTACCA-1                    0.9999537
146P_dedifferentiation_shZFP36L2_3_CACTTCGCATGTGGTT-1  0.9999546
146P_HISC_shCTRL_AAGAACAAGGACACTG-1                    0.9999546
146P_HISC_shCTRL_GAATAGACAGGGATAC-1                    0.9999425
146P_BASE_shZFP36L2_3_CACTGGGTCGCAGTCG-1               0.9999996
146P_HISC_shZFP36L2_4_ACATCCCTCGCCACTT-1               0.9999546
KG146Li_BASE_shZFP36L2_4_AATTTCCCACTCCGAG-1            0.9999539
146P_dedifferentiation_shZFP36L2_4_GGTTCTCGTCTAACGT-1  0.9999706
146P_BASE_shZFP36L2_4_ATCATTCCAAGTGCTT-1               0.9999987
146P_dedifferentiation_shZFP36L2_3_CTCGAGGCACTTCCTG-1  0.9999981
KG146Li_HISC_shCtrl_ATTTCACGTTCGGTCG-1                 0.9999546
KG146Li_HISC_shCtrl_CCTCACAAGGCGTTAG-1                 0.9999546
146P_BASE_shZFP36L2_4_TCTACCGCAGCGGATA-1               0.9999988
KG146Li_HISC_shCtrl_GAATAGAAGCCACAAG-1                 0.9999541
146P_HISC_shCTRL_GCATGATGTGGCAACA-1                    0.9999985
KG146Li_BASE_shCtrl_GGAGGATTCGAAACAA-1                 0.9999963
146P_dedifferentiation_shZFP36L2_4_CACAGGCTCCCGGTAG-1  0.9999546
146Li_dedifferentiation_shZFP36L2_3_GATGAGGTCGCGAAGA-1 0.9999546
KG146Li_BASE_shCtrl_CCCTCAACATCGGTTA-1                 0.9999988
146P_BASE_shCTRL_GGGCTACCATCATCCC-1                    0.9999999
⋮                                                      ⋮
146P_BASE_shCTRL_TCGCACTCAGCGTAGA-1                    1.0000000
146P_dedifferentiation_shCtrl_GACCCAGTCAGCCTTC-1       0.9999961
146P_BASE_shZFP36L2_3_CTACCCATCGAGATGG-1               1.0000000
146P_BASE_shCTRL_CCTTCAGAGTATTCCG-1                    0.9999999
146P_dedifferentiation_shZFP36L2_4_TCCATCGAGTGGATTA-1  0.9995950
146P_dedifferentiation_shZFP36L2_4_TACGTCCAGTCACACT-1  0.9997609
146P_dedifferentiation_shZFP36L2_3_CACGTGGGTGTCTCCT-1  0.9999546
146P_dedifferentiation_shZFP36L2_4_CGTGCTTTCACGAACT-1  0.9999546
KG146Li_BASE_shZFP36L2_3_CATTCCGTCACAATGC-1            0.9999546
146Li_dedifferentiation_shZFP36L2_3_TTTCATGCATAACCCA-1 0.9999546
146P_HISC_shZFP36L2_4_GAGTGTTTCCTGTAAG-1               0.9999546
146P_BASE_shZFP36L2_3_TTCGGTCGTCCCAAAT-1               1.0000000
146P_dedifferentiation_shZFP36L2_3_ACTGCAACAGTGTACT-1  0.9999758
146P_dedifferentiation_shZFP36L2_4_TACCTCGTCGACTCCT-1  0.9998370
146P_BASE_shZFP36L2_4_AGGACGATCTCTCTTC-1               1.0000000
146P_dedifferentiation_shCtrl_AAGACTCGTGATATAG-1       0.9996986
146P_HISC_shZFP36L2_4_CCTCCTCCATATGGCT-1               0.9999999
KG146Li_BASE_shZFP36L2_3_TGAGGAGAGAGTCACG-1            0.9999546
KG146Li_HISC_shCtrl_GTAATGCGTATCAGCT-1                 0.9999546
KG146Li_BASE_shZFP36L2_3_GTGTTAGCATTACTCT-1            0.9999994
146P_HISC_shZFP36L2_4_ATGTCTTCAGTCCCGA-1               0.9999546
KG146Li_BASE_shCtrl_GTTTACTAGATGCTAA-1                 0.9999995
146P_BASE_shCTRL_CCTCAGTCAGGTATGG-1                    1.0000000
146Li_dedifferentiation_shZFP36L2_3_AGGTTGTCATAGAGGC-1 0.9999998
146Li_dedifferentiation_shCtrl_GTATTTCAGTGGCAGT-1      0.9999546
146P_HISC_shCTRL_CCTCACAGTTGGTGTT-1                    0.9999996
146P_BASE_shZFP36L2_3_TCACGCTTCATAGGCT-1               0.9999988
KG146Li_BASE_shZFP36L2_3_TTCTCTCCACCTGCGA-1            0.9998232
146P_dedifferentiation_shZFP36L2_4_TCGGGTGCAAACGGCA-1  0.9999888
146P_BASE_shZFP36L2_4_ACTGCAATCAGTGTTG-1               0.9999998
                                                       cell_size
KG146Li_BASE_shZFP36L2_4_GTCGAATTCGGACGTC-1            15092.094
KG146Li_HISC_shCtrl_GGATCTAAGGTTATAG-1                  8818.770
146P_dedifferentiation_shCtrl_CTCTCAGAGGTAGACC-1       16044.765
146P_HISC_shZFP36L2_4_GTGCAGCAGAGAGGGC-1               11297.001
146P_BASE_shZFP36L2_3_TAGAGTCAGAAAGTCT-1                8557.787
146P_BASE_shCTRL_GGGTCACGTGATACTC-1                    10327.634
KG146Li_BASE_shZFP36L2_4_TTGTTGTAGTCACTGT-1            15651.236
146P_BASE_shCTRL_GGAGATGAGTTCCAGT-1                     9991.460
146P_BASE_shZFP36L2_4_GAGTTTGCAAGACGGT-1                8755.726
146P_BASE_shZFP36L2_3_CTAACCCTCACATCAG-1               11980.288
146P_HISC_shCTRL_TGCAGATAGTCTACCA-1                    14654.359
146P_dedifferentiation_shZFP36L2_3_CACTTCGCATGTGGTT-1  18211.816
146P_HISC_shCTRL_AAGAACAAGGACACTG-1                    16233.369
146P_HISC_shCTRL_GAATAGACAGGGATAC-1                    13692.256
146P_BASE_shZFP36L2_3_CACTGGGTCGCAGTCG-1                6318.487
146P_HISC_shZFP36L2_4_ACATCCCTCGCCACTT-1               14317.689
KG146Li_BASE_shZFP36L2_4_AATTTCCCACTCCGAG-1            16171.607
146P_dedifferentiation_shZFP36L2_4_GGTTCTCGTCTAACGT-1  13140.204
146P_BASE_shZFP36L2_4_ATCATTCCAAGTGCTT-1                5896.261
146P_dedifferentiation_shZFP36L2_3_CTCGAGGCACTTCCTG-1  10169.866
KG146Li_HISC_shCtrl_ATTTCACGTTCGGTCG-1                  8813.801
KG146Li_HISC_shCtrl_CCTCACAAGGCGTTAG-1                 11884.461
146P_BASE_shZFP36L2_4_TCTACCGCAGCGGATA-1                8670.372
KG146Li_HISC_shCtrl_GAATAGAAGCCACAAG-1                  9152.700
146P_HISC_shCTRL_GCATGATGTGGCAACA-1                    11765.455
KG146Li_BASE_shCtrl_GGAGGATTCGAAACAA-1                 10895.949
146P_dedifferentiation_shZFP36L2_4_CACAGGCTCCCGGTAG-1  19002.494
146Li_dedifferentiation_shZFP36L2_3_GATGAGGTCGCGAAGA-1 20449.010
KG146Li_BASE_shCtrl_CCCTCAACATCGGTTA-1                 11432.194
146P_BASE_shCTRL_GGGCTACCATCATCCC-1                     9574.702
⋮                                                      ⋮
146P_BASE_shCTRL_TCGCACTCAGCGTAGA-1                     7779.190
146P_dedifferentiation_shCtrl_GACCCAGTCAGCCTTC-1        9669.040
146P_BASE_shZFP36L2_3_CTACCCATCGAGATGG-1                8702.938
146P_BASE_shCTRL_CCTTCAGAGTATTCCG-1                     8425.778
146P_dedifferentiation_shZFP36L2_4_TCCATCGAGTGGATTA-1  14809.972
146P_dedifferentiation_shZFP36L2_4_TACGTCCAGTCACACT-1  15747.642
146P_dedifferentiation_shZFP36L2_3_CACGTGGGTGTCTCCT-1  18579.568
146P_dedifferentiation_shZFP36L2_4_CGTGCTTTCACGAACT-1  18604.303
KG146Li_BASE_shZFP36L2_3_CATTCCGTCACAATGC-1            16058.603
146Li_dedifferentiation_shZFP36L2_3_TTTCATGCATAACCCA-1 19550.598
146P_HISC_shZFP36L2_4_GAGTGTTTCCTGTAAG-1               12020.424
146P_BASE_shZFP36L2_3_TTCGGTCGTCCCAAAT-1                8202.832
146P_dedifferentiation_shZFP36L2_3_ACTGCAACAGTGTACT-1  14416.614
146P_dedifferentiation_shZFP36L2_4_TACCTCGTCGACTCCT-1  14957.819
146P_BASE_shZFP36L2_4_AGGACGATCTCTCTTC-1                7052.439
146P_dedifferentiation_shCtrl_AAGACTCGTGATATAG-1       14585.607
146P_HISC_shZFP36L2_4_CCTCCTCCATATGGCT-1               11382.521
KG146Li_BASE_shZFP36L2_3_TGAGGAGAGAGTCACG-1            15145.673
KG146Li_HISC_shCtrl_GTAATGCGTATCAGCT-1                 10837.438
KG146Li_BASE_shZFP36L2_3_GTGTTAGCATTACTCT-1             6974.312
146P_HISC_shZFP36L2_4_ATGTCTTCAGTCCCGA-1               14303.469
KG146Li_BASE_shCtrl_GTTTACTAGATGCTAA-1                  7600.457
146P_BASE_shCTRL_CCTCAGTCAGGTATGG-1                     8290.561
146Li_dedifferentiation_shZFP36L2_3_AGGTTGTCATAGAGGC-1  9917.072
146Li_dedifferentiation_shCtrl_GTATTTCAGTGGCAGT-1      17447.799
146P_HISC_shCTRL_CCTCACAGTTGGTGTT-1                    11833.940
146P_BASE_shZFP36L2_3_TCACGCTTCATAGGCT-1                8169.582
KG146Li_BASE_shZFP36L2_3_TTCTCTCCACCTGCGA-1            14554.788
146P_dedifferentiation_shZFP36L2_4_TCGGGTGCAAACGGCA-1  13839.092
146P_BASE_shZFP36L2_4_ACTGCAATCAGTGTTG-1                6241.254
                                                       droplet_efficiency
KG146Li_BASE_shZFP36L2_4_GTCGAATTCGGACGTC-1            1.0152237
KG146Li_HISC_shCtrl_GGATCTAAGGTTATAG-1                 1.1403950
146P_dedifferentiation_shCtrl_CTCTCAGAGGTAGACC-1       1.2350457
146P_HISC_shZFP36L2_4_GTGCAGCAGAGAGGGC-1               0.7787340
146P_BASE_shZFP36L2_3_TAGAGTCAGAAAGTCT-1               1.1305823
146P_BASE_shCTRL_GGGTCACGTGATACTC-1                    1.3651079
KG146Li_BASE_shZFP36L2_4_TTGTTGTAGTCACTGT-1            0.8909897
146P_BASE_shCTRL_GGAGATGAGTTCCAGT-1                    0.9284167
146P_BASE_shZFP36L2_4_GAGTTTGCAAGACGGT-1               1.0266340
146P_BASE_shZFP36L2_3_CTAACCCTCACATCAG-1               1.4054167
146P_HISC_shCTRL_TGCAGATAGTCTACCA-1                    1.0510699
146P_dedifferentiation_shZFP36L2_3_CACTTCGCATGTGGTT-1  1.4232712
146P_HISC_shCTRL_AAGAACAAGGACACTG-1                    1.8593724
146P_HISC_shCTRL_GAATAGACAGGGATAC-1                    0.9375379
146P_BASE_shZFP36L2_3_CACTGGGTCGCAGTCG-1               0.9679142
146P_HISC_shZFP36L2_4_ACATCCCTCGCCACTT-1               1.6423612
KG146Li_BASE_shZFP36L2_4_AATTTCCCACTCCGAG-1            0.9285131
146P_dedifferentiation_shZFP36L2_4_GGTTCTCGTCTAACGT-1  1.0082204
146P_BASE_shZFP36L2_4_ATCATTCCAAGTGCTT-1               0.6211178
146P_dedifferentiation_shZFP36L2_3_CTCGAGGCACTTCCTG-1  0.6550326
KG146Li_HISC_shCtrl_ATTTCACGTTCGGTCG-1                 1.1712897
KG146Li_HISC_shCtrl_CCTCACAAGGCGTTAG-1                 1.5453429
146P_BASE_shZFP36L2_4_TCTACCGCAGCGGATA-1               1.1436623
KG146Li_HISC_shCtrl_GAATAGAAGCCACAAG-1                 1.0319748
146P_HISC_shCTRL_GCATGATGTGGCAACA-1                    0.7121437
KG146Li_BASE_shCtrl_GGAGGATTCGAAACAA-1                 0.7772763
146P_dedifferentiation_shZFP36L2_4_CACAGGCTCCCGGTAG-1  1.0101368
146Li_dedifferentiation_shZFP36L2_3_GATGAGGTCGCGAAGA-1 2.2351768
KG146Li_BASE_shCtrl_CCCTCAACATCGGTTA-1                 0.7531348
146P_BASE_shCTRL_GGGCTACCATCATCCC-1                    0.9942801
⋮                                                      ⋮
146P_BASE_shCTRL_TCGCACTCAGCGTAGA-1                    0.9076140
146P_dedifferentiation_shCtrl_GACCCAGTCAGCCTTC-1       0.6784295
146P_BASE_shZFP36L2_3_CTACCCATCGAGATGG-1               0.8780032
146P_BASE_shCTRL_CCTTCAGAGTATTCCG-1                    1.0014327
146P_dedifferentiation_shZFP36L2_4_TCCATCGAGTGGATTA-1  0.9379468
146P_dedifferentiation_shZFP36L2_4_TACGTCCAGTCACACT-1  0.9374542
146P_dedifferentiation_shZFP36L2_3_CACGTGGGTGTCTCCT-1  1.2291763
146P_dedifferentiation_shZFP36L2_4_CGTGCTTTCACGAACT-1  1.0335413
KG146Li_BASE_shZFP36L2_3_CATTCCGTCACAATGC-1            1.1182404
146Li_dedifferentiation_shZFP36L2_3_TTTCATGCATAACCCA-1 1.4678769
146P_HISC_shZFP36L2_4_GAGTGTTTCCTGTAAG-1               1.4053463
146P_BASE_shZFP36L2_3_TTCGGTCGTCCCAAAT-1               1.0418317
146P_dedifferentiation_shZFP36L2_3_ACTGCAACAGTGTACT-1  0.8582463
146P_dedifferentiation_shZFP36L2_4_TACCTCGTCGACTCCT-1  1.0069344
146P_BASE_shZFP36L2_4_AGGACGATCTCTCTTC-1               0.7229241
146P_dedifferentiation_shCtrl_AAGACTCGTGATATAG-1       1.0286431
146P_HISC_shZFP36L2_4_CCTCCTCCATATGGCT-1               0.7785840
KG146Li_BASE_shZFP36L2_3_TGAGGAGAGAGTCACG-1            1.3525414
KG146Li_HISC_shCtrl_GTAATGCGTATCAGCT-1                 1.5060050
KG146Li_BASE_shZFP36L2_3_GTGTTAGCATTACTCT-1            0.6015872
146P_HISC_shZFP36L2_4_ATGTCTTCAGTCCCGA-1               1.3914906
KG146Li_BASE_shCtrl_GTTTACTAGATGCTAA-1                 0.6605885
146P_BASE_shCTRL_CCTCAGTCAGGTATGG-1                    0.9350149
146Li_dedifferentiation_shZFP36L2_3_AGGTTGTCATAGAGGC-1 0.8439062
146Li_dedifferentiation_shCtrl_GTATTTCAGTGGCAGT-1      1.2198943
146P_HISC_shCTRL_CCTCACAGTTGGTGTT-1                    0.7666510
146P_BASE_shZFP36L2_3_TCACGCTTCATAGGCT-1               1.1361125
KG146Li_BASE_shZFP36L2_3_TTCTCTCCACCTGCGA-1            0.9036257
146P_dedifferentiation_shZFP36L2_4_TCGGGTGCAAACGGCA-1  0.8149741
146P_BASE_shZFP36L2_4_ACTGCAATCAGTGTTG-1               0.7150114
                                                       n_genes_by_counts
KG146Li_BASE_shZFP36L2_4_GTCGAATTCGGACGTC-1            4410
KG146Li_HISC_shCtrl_GGATCTAAGGTTATAG-1                 2946
146P_dedifferentiation_shCtrl_CTCTCAGAGGTAGACC-1       3376
146P_HISC_shZFP36L2_4_GTGCAGCAGAGAGGGC-1               2657
146P_BASE_shZFP36L2_3_TAGAGTCAGAAAGTCT-1               3076
146P_BASE_shCTRL_GGGTCACGTGATACTC-1                    3291
KG146Li_BASE_shZFP36L2_4_TTGTTGTAGTCACTGT-1            3869
146P_BASE_shCTRL_GGAGATGAGTTCCAGT-1                    2664
146P_BASE_shZFP36L2_4_GAGTTTGCAAGACGGT-1               2686
146P_BASE_shZFP36L2_3_CTAACCCTCACATCAG-1               4598
146P_HISC_shCTRL_TGCAGATAGTCTACCA-1                    3856
146P_dedifferentiation_shZFP36L2_3_CACTTCGCATGTGGTT-1  5172
146P_HISC_shCTRL_AAGAACAAGGACACTG-1                    5655
146P_HISC_shCTRL_GAATAGACAGGGATAC-1                    3302
146P_BASE_shZFP36L2_3_CACTGGGTCGCAGTCG-1               2032
146P_HISC_shZFP36L2_4_ACATCCCTCGCCACTT-1               5510
KG146Li_BASE_shZFP36L2_4_AATTTCCCACTCCGAG-1            4006
146P_dedifferentiation_shZFP36L2_4_GGTTCTCGTCTAACGT-1  3108
146P_BASE_shZFP36L2_4_ATCATTCCAAGTGCTT-1               1114
146P_dedifferentiation_shZFP36L2_3_CTCGAGGCACTTCCTG-1  1095
KG146Li_HISC_shCtrl_ATTTCACGTTCGGTCG-1                 2705
KG146Li_HISC_shCtrl_CCTCACAAGGCGTTAG-1                 4579
146P_BASE_shZFP36L2_4_TCTACCGCAGCGGATA-1               3122
KG146Li_HISC_shCtrl_GAATAGAAGCCACAAG-1                 2483
146P_HISC_shCTRL_GCATGATGTGGCAACA-1                    1584
KG146Li_BASE_shCtrl_GGAGGATTCGAAACAA-1                 2207
146P_dedifferentiation_shZFP36L2_4_CACAGGCTCCCGGTAG-1  3729
146Li_dedifferentiation_shZFP36L2_3_GATGAGGTCGCGAAGA-1 5912
KG146Li_BASE_shCtrl_CCCTCAACATCGGTTA-1                 2625
146P_BASE_shCTRL_GGGCTACCATCATCCC-1                    2952
⋮                                                      ⋮
146P_BASE_shCTRL_TCGCACTCAGCGTAGA-1                    2288
146P_dedifferentiation_shCtrl_GACCCAGTCAGCCTTC-1        961
146P_BASE_shZFP36L2_3_CTACCCATCGAGATGG-1               2376
146P_BASE_shCTRL_CCTTCAGAGTATTCCG-1                    2447
146P_dedifferentiation_shZFP36L2_4_TCCATCGAGTGGATTA-1  3019
146P_dedifferentiation_shZFP36L2_4_TACGTCCAGTCACACT-1  1905
146P_dedifferentiation_shZFP36L2_3_CACGTGGGTGTCTCCT-1  3878
146P_dedifferentiation_shZFP36L2_4_CGTGCTTTCACGAACT-1  3785
KG146Li_BASE_shZFP36L2_3_CATTCCGTCACAATGC-1            4752
146Li_dedifferentiation_shZFP36L2_3_TTTCATGCATAACCCA-1 6008
146P_HISC_shZFP36L2_4_GAGTGTTTCCTGTAAG-1               4509
146P_BASE_shZFP36L2_3_TTCGGTCGTCCCAAAT-1               2605
146P_dedifferentiation_shZFP36L2_3_ACTGCAACAGTGTACT-1  3180
146P_dedifferentiation_shZFP36L2_4_TACCTCGTCGACTCCT-1  2950
146P_BASE_shZFP36L2_4_AGGACGATCTCTCTTC-1               1303
146P_dedifferentiation_shCtrl_AAGACTCGTGATATAG-1       3337
146P_HISC_shZFP36L2_4_CCTCCTCCATATGGCT-1               2483
KG146Li_BASE_shZFP36L2_3_TGAGGAGAGAGTCACG-1            4940
KG146Li_HISC_shCtrl_GTAATGCGTATCAGCT-1                 4043
KG146Li_BASE_shZFP36L2_3_GTGTTAGCATTACTCT-1            1059
146P_HISC_shZFP36L2_4_ATGTCTTCAGTCCCGA-1               5008
KG146Li_BASE_shCtrl_GTTTACTAGATGCTAA-1                 1011
146P_BASE_shCTRL_CCTCAGTCAGGTATGG-1                    2017
146Li_dedifferentiation_shZFP36L2_3_AGGTTGTCATAGAGGC-1 2024
146Li_dedifferentiation_shCtrl_GTATTTCAGTGGCAGT-1      4603
146P_HISC_shCTRL_CCTCACAGTTGGTGTT-1                    2484
146P_BASE_shZFP36L2_3_TCACGCTTCATAGGCT-1               2918
KG146Li_BASE_shZFP36L2_3_TTCTCTCCACCTGCGA-1            3661
146P_dedifferentiation_shZFP36L2_4_TCGGGTGCAAACGGCA-1  2548
146P_BASE_shZFP36L2_4_ACTGCAATCAGTGTTG-1               1153

In [16]:
# Extract count matrix from the raw layer
count_matrix <- adata$raw$X
#count_matrix <- adata$X
#count_matrix <- as(count_matrix, "matrix")
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)

In [17]:
count_matrix

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [2,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [3,] 2    2    3    4    4    4    4    5    3    4     ⋯     0     3
 [4,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [5,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [6,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [7,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [8,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
 [9,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[10,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[12,] 0    2    2    0    2    0    1    3    2    0     ⋯     3     2
[13,] 4    2    3    2    3    3    3    3    3    0     ⋯     0     3
[14,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[19,] 2    2    0    0    0    0    0    0    0    0     ⋯     0     1
[20,] 4    2    3    2    1    2    1    2    2    0     ⋯     2     3
[21,] 1    2    2    3    0    0    0    3    3    0     ⋯     2     3
[22,] 0    2    3    0    1    2    2    1    1    0     ⋯     3     3
[23,] 0    3    3    0    3    3    3    2    1    3     ⋯     3     3
[24,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[25,] 0    1    1    0    0    2    1    0    1    0     ⋯     2     1
[26,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[27,] 3    3    2    0    3    3    3    1    1    0     ⋯     2     2
[28,] 2    1    1    0    1    0    1    0    0    0     ⋯     0     1
[29,] 2    2    2    0    1    0    0    2    3    0     ⋯     2     2
[30,] 1    1    2    0    1    3    2    2    1    0     ⋯     3     2
[31,] ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮     ⋱     ⋮     ⋮
[32,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     1
[33,] 1    1    1    0    0    1    1    0    1    0     ⋯     2     1
[34,] 0    1    1    0    0    2    1    1    0    3     ⋯     0     2
[35,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0
[36,] 1    1    0    0    0    2    1    0    0    0     ⋯     0     0
[37,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[38,] 0    1    1    2    0    1    1    3    1    0     ⋯     0     3
[39,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[40,] 0    0    1    0    1    0    1    1    0    0     ⋯     0     1
[41,] 0    0    1    0    1    0    0    0    0    0     ⋯     0     0
[42,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[43,] 0    1    1    0    1    2    1    0    0    3     ⋯     0     2
[44,] 2    0    0    0    1    2    1    1    0    0     ⋯     0     2
[45,] 5    3    3    4    3    3    4    4    4    4     ⋯     0     4
[46,] 5    3    3    3    4    4    4    5    4    3     ⋯     0     4
[47,] 0    1    2    0    1    2    1    0    1    0     ⋯     2     2
[48,] 0    0    0    0    1    1    1    3    0    0     ⋯     0     0
[49,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[50,] 1    1    2    2    1    1    1    1    2    0     ⋯     2     2
[51,] 1    1    2    0    1    2    1    1    1    0     ⋯     2     2
[52,] 0    1    2    0    1    0    2    0    2    0     ⋯     2     1
[53,] 3    1    3    0    0    1    0    0    3    0     ⋯     2     0
[54,] 0    4    4    0    5    3    0    0    4    0     ⋯     4     3
[55,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0
[56,] 0    0    0    0    0    0    1    0    1    0     ⋯     0     2
[57,] 3    2    3    2    3    4    2    3    3    0     ⋯     0     3
[58,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0
[59,] 3    1    3    0    1    3    3    2    2    3     ⋯     3     3
[60,] 0    2    1    2    1    0    1    1    1    3     ⋯     0     2
[61,] 2    1    1    3    2    2    2    1    1    3     ⋯     0     2
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0
 [2,] 0     0     0     0     0     0     0     0
 [3,] 3     4     4     3     4     4     3     3
 [4,] 0     0     0     0     0     0     0     0
 [5,] 0     0     0     0     0     0     0     0
 [6,] 0     0     0     0     1     0     0     1
 [7,] 0     0     0     0     0     0     0     0
 [8,] 0     0     0     0     0     0     0     0
 [9,] 0     0     0     0     0     0     1     0
[10,] 0     0     0     0     1     0     0     0
[11,] 0     0     0     0     0     0     0     0
[12,] 2     2     1     2     1     2     2     1
[13,] 3     4     3     3     3     3     3     3
[14,] 0     0     0     0     0     0     0     0
[15,] 0     0     0     0     0     0     0     0
[16,] 1     0     0     0     1     0     1     1
[17,] 0     0     0     0     0     0     0     0
[18,] 0     0     0     0     0     0     0     0
[19,] 1     0     0     1     0     0     1     2
[20,] 3     0     2     3     1     0     2     3
[21,] 2     3     2     2     2     2     2     2
[22,] 2     3     3     3     2     2     2     2
[23,] 3     2     3     3     3     2     3     3
[24,] 0     0     0     0     0     0     0     0
[25,] 0     2     2     2     1     0     2     1
[26,] 0     0     0     0     0     0     0     0
[27,] 3     2     2     3     3     2     3     2
[28,] 1     2     2     1     0     3     0     1
[29,] 2     2     2     3     1     2     2     3
[30,] 3     2     0     1     3     0     3     2
[31,] ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮
[32,] 1     0     0     1     1     0     0     1
[33,] 2     0     0     1     0     2     0     1
[34,] 1     0     0     1     3     2     1     1
[35,] 1     0     0     1     1     0     1     1
[36,] 2     0     1     2     1     2     2     2
[37,] 0     0     0     0     0     0     0     0
[38,] 2     3     1     3     1     2     1     2
[39,] 0     0     0     0     0     0     0     0
[40,] 1     0     2     1     1     0     1     0
[41,] 0     0     0     1     1     0     0     0
[42,] 0     0     0     0     0     0     0     0
[43,] 1     0     0     1     0     0     0     0
[44,] 1     0     0     0     1     0     1     1
[45,] 3     4     2     4     5     4     5     3
[46,] 3     5     2     3     5     4     4     3
[47,] 2     0     1     1     2     0     1     1
[48,] 1     0     1     0     2     2     1     1
[49,] 0     0     0     0     1     0     0     0
[50,] 2     2     0     2     1     2     1     0
[51,] 2     3     1     2     2     0     2     1
[52,] 2     2     2     1     1     3     1     1
[53,] 2     2     3     3     6     3     1     2
[54,] 4     0     4     4     2     2     2     2
[55,] 0     0     0     0     1     0     0     0
[56,] 1     0     0     0     1     0     0     0
[57,] 3     3     2     3     3     3     3     3
[58,] 1     0     0     0     0     0     0     0
[59,] 2     3     3     2     4     3     3     3
[60,] 1     0     0     2     0     0     1     3
[61,] 2     0     1     2     3     2     2     2

In [27]:
# Extract sample names from row names
sample_names <- rownames(adata$X)

# Assuming 'adata' is your AnnData object

# Extract sample names from row names
sample_names <- rownames(adata$X)

# Create a new column 'Tumor_Site' based on sample names
adata$obs$Tumor_Site <- ifelse(grepl("146P", sample_names), "Primary", 
                               ifelse(grepl("146Li", sample_names), "Metastatic", NA))

# Create a new column 'Culture_Media' based on sample names
adata$obs$Culture_Media <- ifelse(grepl("BASE", sample_names, ignore.case = TRUE), "BASE", 
                                  ifelse(grepl("HISC", sample_names, ignore.case = TRUE), "HISC",
                                  ifelse(grepl("dedifferentiation", sample_names, ignore.case = TRUE), "Dedifferentiated", "Unknown")))

# Create a new column 'ZFP_Expression' based on sample names
adata$obs$ZFP_Expression <- ifelse(grepl("CTRL", sample_names, ignore.case = TRUE), "CTRL", 
                                  ifelse(grepl("ZFP", sample_names, ignore.case = TRUE), "ZFPKD", "Unknown"))

In [28]:
adata$obs

                                                       background_fraction
146P_HISC_shCTRL_CCGGACACACCACATA-1                    0.02229144
146P_dedifferentiation_shZFP36L2_3_ACTTTGTTCGCTGTTC-1  0.05122740
KG146Li_BASE_shZFP36L2_3_GTGGTTAGTTGGGAAC-1            0.00761133
146P_dedifferentiation_shCtrl_GGGTCTGTCGATGCTA-1       0.03223666
146P_HISC_shZFP36L2_3_TGGAACTCAACCTAAC-1               0.01331819
146Li_dedifferentiation_shZFP36L2_4_TCCCATGAGTGACCTT-1 0.03227444
146P_dedifferentiation_shZFP36L2_3_GGCGTCAGTCCAGCGT-1  0.07923496
146P_BASE_shZFP36L2_3_TCTTTGAGTGCAGGAT-1               0.03844221
146P_dedifferentiation_shZFP36L2_3_CATCAAGTCTCGTGAA-1  0.03585139
146P_BASE_shZFP36L2_3_GTGTGATTCGGAGTAG-1               0.04250559
146P_HISC_shZFP36L2_4_AACACACAGTTTGTCG-1               0.09344580
KG146Li_BASE_shCtrl_ATACCGACAGTAGATA-1                 0.01872247
146P_HISC_shZFP36L2_4_CGAGGAACACTGTTCC-1               0.01423983
146P_BASE_shZFP36L2_3_GGTAATCGTAGTTCCA-1               0.18107232
146P_dedifferentiation_shCtrl_GACCCAGAGTAGAGTT-1       0.02623233
KG146Li_BASE_shZFP36L2_3_TGGGAAGGTCCAGTTA-1            0.01884101
KG146Li_HISC_shCtrl_TCAGTCCCAAGAAACT-1                 0.01536235
146Li_dedifferentiation_shCtrl_GACTATGAGGAGACCT-1      0.01166079
KG146Li_BASE_shZFP36L2_3_TCAGGTAAGACCATAA-1            0.01315789
KG146Li_HISC_shCtrl_TCGAAGTTCTGATTCT-1                 0.02086677
146P_HISC_shZFP36L2_4_CCGGACAAGGCAATGC-1               0.02515178
146P_HISC_shZFP36L2_4_CCTCTCCAGTCGAAGC-1               0.32901540
KG146Li_BASE_shCtrl_CCCTGATAGGGCGAGA-1                 0.11694045
146Li_dedifferentiation_shCtrl_CGATCGGCACAAGTGG-1      0.02137668
146P_HISC_shZFP36L2_3_TCATTTGTCATGCCGG-1               0.07759313
146P_dedifferentiation_shZFP36L2_3_CTCAGGGGTGAGGAAA-1  0.03171549
146P_dedifferentiation_shCtrl_CAGGGCTGTGTTAACC-1       0.04242046
146P_HISC_shZFP36L2_3_TGACGCGAGGCTCAAG-1               0.01321342
KG146Li_HISC_shCtrl_CTACGGGTCACCCTCA-1                 0.01045911
146P_HISC_shZFP36L2_3_GAGGCCTTCACCGCTT-1               0.02074449
⋮                                                      ⋮
KG146Li_BASE_shZFP36L2_3_ACCAAACGTACCGGCT-1            0.045924696
146P_dedifferentiation_shZFP36L2_4_TGATCAGAGCCTATTG-1  0.044994526
146P_HISC_shZFP36L2_4_ACGTTCCCACACAGCC-1               0.192726256
146P_BASE_shZFP36L2_3_TCTGTCGGTCAACGCC-1               0.102660078
KG146Li_HISC_shCtrl_TTTCATGAGAGTTGAT-1                 0.016214426
146P_HISC_shZFP36L2_4_CCTTTGGCAGGTGTGA-1               0.029859369
KG146Li_HISC_shZFP36L2_3_GTGTTAGGTTGCGGAA-1            0.029304024
146P_HISC_shZFP36L2_4_TTCCGTGCAAAGAGTT-1               0.019973701
146P_dedifferentiation_shZFP36L2_4_CCACGTTAGACGTCCC-1  0.060838743
146P_HISC_shZFP36L2_3_CTGTCGTAGTGAGGTC-1               0.018064075
146P_HISC_shCTRL_AGTGACTAGTTACGTC-1                    0.243582675
146P_dedifferentiation_shCtrl_GATGAGGGTATATGGA-1       0.076092191
146P_BASE_shZFP36L2_4_GTCGTTCGTGCCTTCT-1               0.130899123
146P_HISC_shCTRL_ACTATCTGTGATGGCA-1                    0.124999977
146P_HISC_shCTRL_TTGGTTTGTCCCGCAA-1                    0.107016835
146P_dedifferentiation_shZFP36L2_3_CGTTCTGGTCCGGTGT-1  0.135726285
146P_BASE_shZFP36L2_4_TGAGTCAAGCACCAGA-1               0.003669779
146P_dedifferentiation_shZFP36L2_4_CGTAATGTCCCAGGAC-1  0.035607092
146P_BASE_shCTRL_CATGGATAGCACTCGC-1                    0.092384719
KG146Li_BASE_shZFP36L2_3_GACCGTGCATGAGAAT-1            0.031105988
146P_dedifferentiation_shZFP36L2_4_TACCTCGAGGGAGGGT-1  0.116295751
146P_BASE_shCTRL_GCACATAAGTCGGGAT-1                    0.016575822
146P_HISC_shZFP36L2_4_TTTGACTCAACGCCCA-1               0.108875451
146P_dedifferentiation_shZFP36L2_4_AGCGCCAAGACTCTTG-1  0.074788243
KG146Li_HISC_shZFP36L2_3_CAGGTATCATCCTCAC-1            0.027839228
146Li_dedifferentiation_shZFP36L2_4_AAATGGAAGCGGTAAC-1 0.018783541
146P_BASE_shZFP36L2_3_TCGTGGGAGCTCTTCC-1               0.056775928
146Li_dedifferentiation_shCtrl_TAGACCAAGTAGACCG-1      0.022373934
146P_dedifferentiation_shCtrl_GGGCGTTAGAAGGCTC-1       0.092005838
146P_BASE_shZFP36L2_4_GTCTACCAGGTAGCAC-1               0.010247074
                                                       cell_probability
146P_HISC_shCTRL_CCGGACACACCACATA-1                    0.9999546
146P_dedifferentiation_shZFP36L2_3_ACTTTGTTCGCTGTTC-1  0.9999504
KG146Li_BASE_shZFP36L2_3_GTGGTTAGTTGGGAAC-1            0.9999546
146P_dedifferentiation_shCtrl_GGGTCTGTCGATGCTA-1       0.9999546
146P_HISC_shZFP36L2_3_TGGAACTCAACCTAAC-1               0.9999546
146Li_dedifferentiation_shZFP36L2_4_TCCCATGAGTGACCTT-1 0.9999546
146P_dedifferentiation_shZFP36L2_3_GGCGTCAGTCCAGCGT-1  0.9999856
146P_BASE_shZFP36L2_3_TCTTTGAGTGCAGGAT-1               0.9999993
146P_dedifferentiation_shZFP36L2_3_CATCAAGTCTCGTGAA-1  0.9999546
146P_BASE_shZFP36L2_3_GTGTGATTCGGAGTAG-1               0.9999996
146P_HISC_shZFP36L2_4_AACACACAGTTTGTCG-1               0.9999998
KG146Li_BASE_shCtrl_ATACCGACAGTAGATA-1                 0.9999481
146P_HISC_shZFP36L2_4_CGAGGAACACTGTTCC-1               0.9999546
146P_BASE_shZFP36L2_3_GGTAATCGTAGTTCCA-1               0.9999996
146P_dedifferentiation_shCtrl_GACCCAGAGTAGAGTT-1       0.9999546
KG146Li_BASE_shZFP36L2_3_TGGGAAGGTCCAGTTA-1            0.9999546
KG146Li_HISC_shCtrl_TCAGTCCCAAGAAACT-1                 0.9999546
146Li_dedifferentiation_shCtrl_GACTATGAGGAGACCT-1      0.9999546
KG146Li_BASE_shZFP36L2_3_TCAGGTAAGACCATAA-1            0.9999546
KG146Li_HISC_shCtrl_TCGAAGTTCTGATTCT-1                 0.9999546
146P_HISC_shZFP36L2_4_CCGGACAAGGCAATGC-1               0.9999326
146P_HISC_shZFP36L2_4_CCTCTCCAGTCGAAGC-1               0.9999981
KG146Li_BASE_shCtrl_CCCTGATAGGGCGAGA-1                 0.9999030
146Li_dedifferentiation_shCtrl_CGATCGGCACAAGTGG-1      0.9997950
146P_HISC_shZFP36L2_3_TCATTTGTCATGCCGG-1               0.9999883
146P_dedifferentiation_shZFP36L2_3_CTCAGGGGTGAGGAAA-1  0.9999546
146P_dedifferentiation_shCtrl_CAGGGCTGTGTTAACC-1       0.9999546
146P_HISC_shZFP36L2_3_TGACGCGAGGCTCAAG-1               0.9999546
KG146Li_HISC_shCtrl_CTACGGGTCACCCTCA-1                 0.9999546
146P_HISC_shZFP36L2_3_GAGGCCTTCACCGCTT-1               0.9999542
⋮                                                      ⋮
KG146Li_BASE_shZFP36L2_3_ACCAAACGTACCGGCT-1            0.9999560
146P_dedifferentiation_shZFP36L2_4_TGATCAGAGCCTATTG-1  0.9999545
146P_HISC_shZFP36L2_4_ACGTTCCCACACAGCC-1               0.9999999
146P_BASE_shZFP36L2_3_TCTGTCGGTCAACGCC-1               0.9999999
KG146Li_HISC_shCtrl_TTTCATGAGAGTTGAT-1                 0.9999546
146P_HISC_shZFP36L2_4_CCTTTGGCAGGTGTGA-1               0.9999884
KG146Li_HISC_shZFP36L2_3_GTGTTAGGTTGCGGAA-1            0.9999988
146P_HISC_shZFP36L2_4_TTCCGTGCAAAGAGTT-1               0.9999546
146P_dedifferentiation_shZFP36L2_4_CCACGTTAGACGTCCC-1  0.9996746
146P_HISC_shZFP36L2_3_CTGTCGTAGTGAGGTC-1               0.9999546
146P_HISC_shCTRL_AGTGACTAGTTACGTC-1                    0.9999998
146P_dedifferentiation_shCtrl_GATGAGGGTATATGGA-1       0.9999715
146P_BASE_shZFP36L2_4_GTCGTTCGTGCCTTCT-1               1.0000000
146P_HISC_shCTRL_ACTATCTGTGATGGCA-1                    0.9999996
146P_HISC_shCTRL_TTGGTTTGTCCCGCAA-1                    0.9999996
146P_dedifferentiation_shZFP36L2_3_CGTTCTGGTCCGGTGT-1  0.9999998
146P_BASE_shZFP36L2_4_TGAGTCAAGCACCAGA-1               0.9999546
146P_dedifferentiation_shZFP36L2_4_CGTAATGTCCCAGGAC-1  0.9999545
146P_BASE_shCTRL_CATGGATAGCACTCGC-1                    1.0000000
KG146Li_BASE_shZFP36L2_3_GACCGTGCATGAGAAT-1            0.9999001
146P_dedifferentiation_shZFP36L2_4_TACCTCGAGGGAGGGT-1  0.9999992
146P_BASE_shCTRL_GCACATAAGTCGGGAT-1                    0.9999546
146P_HISC_shZFP36L2_4_TTTGACTCAACGCCCA-1               1.0000000
146P_dedifferentiation_shZFP36L2_4_AGCGCCAAGACTCTTG-1  0.9998584
KG146Li_HISC_shZFP36L2_3_CAGGTATCATCCTCAC-1            0.9999983
146Li_dedifferentiation_shZFP36L2_4_AAATGGAAGCGGTAAC-1 0.9999460
146P_BASE_shZFP36L2_3_TCGTGGGAGCTCTTCC-1               1.0000000
146Li_dedifferentiation_shCtrl_TAGACCAAGTAGACCG-1      0.9998813
146P_dedifferentiation_shCtrl_GGGCGTTAGAAGGCTC-1       0.9999988
146P_BASE_shZFP36L2_4_GTCTACCAGGTAGCAC-1               0.9999546
                                                       cell_size
146P_HISC_shCTRL_CCGGACACACCACATA-1                    14050.673
146P_dedifferentiation_shZFP36L2_3_ACTTTGTTCGCTGTTC-1  14127.893
KG146Li_BASE_shZFP36L2_3_GTGGTTAGTTGGGAAC-1            14619.754
146P_dedifferentiation_shCtrl_GGGTCTGTCGATGCTA-1       15622.843
146P_HISC_shZFP36L2_3_TGGAACTCAACCTAAC-1               15020.916
146Li_dedifferentiation_shZFP36L2_4_TCCCATGAGTGACCTT-1 16821.025
146P_dedifferentiation_shZFP36L2_3_GGCGTCAGTCCAGCGT-1  14131.530
146P_BASE_shZFP36L2_3_TCTTTGAGTGCAGGAT-1                9622.292
146P_dedifferentiation_shZFP36L2_3_CATCAAGTCTCGTGAA-1  16797.027
146P_BASE_shZFP36L2_3_GTGTGATTCGGAGTAG-1                8213.016
146P_HISC_shZFP36L2_4_AACACACAGTTTGTCG-1               10089.318
KG146Li_BASE_shCtrl_ATACCGACAGTAGATA-1                 14186.988
146P_HISC_shZFP36L2_4_CGAGGAACACTGTTCC-1               13892.567
146P_BASE_shZFP36L2_3_GGTAATCGTAGTTCCA-1                6272.510
146P_dedifferentiation_shCtrl_GACCCAGAGTAGAGTT-1       15994.257
KG146Li_BASE_shZFP36L2_3_TGGGAAGGTCCAGTTA-1            13048.780
KG146Li_HISC_shCtrl_TCAGTCCCAAGAAACT-1                  8231.066
146Li_dedifferentiation_shCtrl_GACTATGAGGAGACCT-1      19532.557
KG146Li_BASE_shZFP36L2_3_TCAGGTAAGACCATAA-1            13570.889
KG146Li_HISC_shCtrl_TCGAAGTTCTGATTCT-1                  8568.346
146P_HISC_shZFP36L2_4_CCGGACAAGGCAATGC-1               13160.221
146P_HISC_shZFP36L2_4_CCTCTCCAGTCGAAGC-1                6216.714
KG146Li_BASE_shCtrl_CCCTGATAGGGCGAGA-1                  8582.404
146Li_dedifferentiation_shCtrl_CGATCGGCACAAGTGG-1      13564.381
146P_HISC_shZFP36L2_3_TCATTTGTCATGCCGG-1               10245.437
146P_dedifferentiation_shZFP36L2_3_CTCAGGGGTGAGGAAA-1  16429.861
146P_dedifferentiation_shCtrl_CAGGGCTGTGTTAACC-1       16286.930
146P_HISC_shZFP36L2_3_TGACGCGAGGCTCAAG-1               15168.584
KG146Li_HISC_shCtrl_CTACGGGTCACCCTCA-1                 11425.557
146P_HISC_shZFP36L2_3_GAGGCCTTCACCGCTT-1               13747.733
⋮                                                      ⋮
KG146Li_BASE_shZFP36L2_3_ACCAAACGTACCGGCT-1             9463.442
146P_dedifferentiation_shZFP36L2_4_TGATCAGAGCCTATTG-1  14678.863
146P_HISC_shZFP36L2_4_ACGTTCCCACACAGCC-1                7680.894
146P_BASE_shZFP36L2_3_TCTGTCGGTCAACGCC-1                6916.726
KG146Li_HISC_shCtrl_TTTCATGAGAGTTGAT-1                  8850.770
146P_HISC_shZFP36L2_4_CCTTTGGCAGGTGTGA-1               12123.531
KG146Li_HISC_shZFP36L2_3_GTGTTAGGTTGCGGAA-1             6610.542
146P_HISC_shZFP36L2_4_TTCCGTGCAAAGAGTT-1               12340.654
146P_dedifferentiation_shZFP36L2_4_CCACGTTAGACGTCCC-1  15905.471
146P_HISC_shZFP36L2_3_CTGTCGTAGTGAGGTC-1               12927.654
146P_HISC_shCTRL_AGTGACTAGTTACGTC-1                     7904.016
146P_dedifferentiation_shCtrl_GATGAGGGTATATGGA-1       13768.832
146P_BASE_shZFP36L2_4_GTCGTTCGTGCCTTCT-1                7737.150
146P_HISC_shCTRL_ACTATCTGTGATGGCA-1                     9341.538
146P_HISC_shCTRL_TTGGTTTGTCCCGCAA-1                     9661.234
146P_dedifferentiation_shZFP36L2_3_CGTTCTGGTCCGGTGT-1  11578.983
146P_BASE_shZFP36L2_4_TGAGTCAAGCACCAGA-1               18296.037
146P_dedifferentiation_shZFP36L2_4_CGTAATGTCCCAGGAC-1  15571.035
146P_BASE_shCTRL_CATGGATAGCACTCGC-1                     7602.487
KG146Li_BASE_shZFP36L2_3_GACCGTGCATGAGAAT-1            12661.443
146P_dedifferentiation_shZFP36L2_4_TACCTCGAGGGAGGGT-1  13423.173
146P_BASE_shCTRL_GCACATAAGTCGGGAT-1                     9614.192
146P_HISC_shZFP36L2_4_TTTGACTCAACGCCCA-1                8954.314
146P_dedifferentiation_shZFP36L2_4_AGCGCCAAGACTCTTG-1  14019.967
KG146Li_HISC_shZFP36L2_3_CAGGTATCATCCTCAC-1             6625.653
146Li_dedifferentiation_shZFP36L2_4_AAATGGAAGCGGTAAC-1 15664.033
146P_BASE_shZFP36L2_3_TCGTGGGAGCTCTTCC-1                8108.023
146Li_dedifferentiation_shCtrl_TAGACCAAGTAGACCG-1      14368.451
146P_dedifferentiation_shCtrl_GGGCGTTAGAAGGCTC-1       11828.569
146P_BASE_shZFP36L2_4_GTCTACCAGGTAGCAC-1               12209.311
                                                       droplet_efficiency
146P_HISC_shCTRL_CCGGACACACCACATA-1                    1.3242252
146P_dedifferentiation_shZFP36L2_3_ACTTTGTTCGCTGTTC-1  1.1506593
KG146Li_BASE_shZFP36L2_3_GTGGTTAGTTGGGAAC-1            2.0058451
146P_dedifferentiation_shCtrl_GGGTCTGTCGATGCTA-1       1.3579359
146P_HISC_shZFP36L2_3_TGGAACTCAACCTAAC-1               1.4536747
146Li_dedifferentiation_shZFP36L2_4_TCCCATGAGTGACCTT-1 1.1827675
146P_dedifferentiation_shZFP36L2_3_GGCGTCAGTCCAGCGT-1  0.8634863
146P_BASE_shZFP36L2_3_TCTTTGAGTGCAGGAT-1               0.9532719
146P_dedifferentiation_shZFP36L2_3_CATCAAGTCTCGTGAA-1  1.1660888
146P_BASE_shZFP36L2_3_GTGTGATTCGGAGTAG-1               1.0980576
146P_HISC_shZFP36L2_4_AACACACAGTTTGTCG-1               0.9169322
KG146Li_BASE_shCtrl_ATACCGACAGTAGATA-1                 0.9942531
146P_HISC_shZFP36L2_4_CGAGGAACACTGTTCC-1               1.3527185
146P_BASE_shZFP36L2_3_GGTAATCGTAGTTCCA-1               0.6841414
146P_dedifferentiation_shCtrl_GACCCAGAGTAGAGTT-1       1.6143528
KG146Li_BASE_shZFP36L2_3_TGGGAAGGTCCAGTTA-1            1.4503179
KG146Li_HISC_shCtrl_TCAGTCCCAAGAAACT-1                 1.2298461
146Li_dedifferentiation_shCtrl_GACTATGAGGAGACCT-1      1.4577793
KG146Li_BASE_shZFP36L2_3_TCAGGTAAGACCATAA-1            1.3654966
KG146Li_HISC_shCtrl_TCGAAGTTCTGATTCT-1                 1.2218008
146P_HISC_shZFP36L2_4_CCGGACAAGGCAATGC-1               1.1044436
146P_HISC_shZFP36L2_4_CCTCTCCAGTCGAAGC-1               0.5121136
KG146Li_BASE_shCtrl_CCCTGATAGGGCGAGA-1                 0.7921349
146Li_dedifferentiation_shCtrl_CGATCGGCACAAGTGG-1      1.2351983
146P_HISC_shZFP36L2_3_TCATTTGTCATGCCGG-1               0.8719237
146P_dedifferentiation_shZFP36L2_3_CTCAGGGGTGAGGAAA-1  1.2865829
146P_dedifferentiation_shCtrl_CAGGGCTGTGTTAACC-1       1.1446002
146P_HISC_shZFP36L2_3_TGACGCGAGGCTCAAG-1               1.4772117
KG146Li_HISC_shCtrl_CTACGGGTCACCCTCA-1                 1.4000847
146P_HISC_shZFP36L2_3_GAGGCCTTCACCGCTT-1               1.1465402
⋮                                                      ⋮
KG146Li_BASE_shZFP36L2_3_ACCAAACGTACCGGCT-1            1.5114586
146P_dedifferentiation_shZFP36L2_4_TGATCAGAGCCTATTG-1  1.1811917
146P_HISC_shZFP36L2_4_ACGTTCCCACACAGCC-1               0.6286333
146P_BASE_shZFP36L2_3_TCTGTCGGTCAACGCC-1               0.9029708
KG146Li_HISC_shCtrl_TTTCATGAGAGTTGAT-1                 1.1428349
146P_HISC_shZFP36L2_4_CCTTTGGCAGGTGTGA-1               0.9943333
KG146Li_HISC_shZFP36L2_3_GTGTTAGGTTGCGGAA-1            0.9121726
146P_HISC_shZFP36L2_4_TTCCGTGCAAAGAGTT-1               1.5034194
146P_dedifferentiation_shZFP36L2_4_CCACGTTAGACGTCCC-1  0.8676339
146P_HISC_shZFP36L2_3_CTGTCGTAGTGAGGTC-1               1.3059943
146P_HISC_shCTRL_AGTGACTAGTTACGTC-1                    0.5885063
146P_dedifferentiation_shCtrl_GATGAGGGTATATGGA-1       0.9025362
146P_BASE_shZFP36L2_4_GTCGTTCGTGCCTTCT-1               0.6205681
146P_HISC_shCTRL_ACTATCTGTGATGGCA-1                    0.7015424
146P_HISC_shCTRL_TTGGTTTGTCCCGCAA-1                    0.6376060
146P_dedifferentiation_shZFP36L2_3_CGTTCTGGTCCGGTGT-1  0.7672217
146P_BASE_shZFP36L2_4_TGAGTCAAGCACCAGA-1               2.0012431
146P_dedifferentiation_shZFP36L2_4_CGTAATGTCCCAGGAC-1  1.1030719
146P_BASE_shCTRL_CATGGATAGCACTCGC-1                    0.9174029
KG146Li_BASE_shZFP36L2_3_GACCGTGCATGAGAAT-1            0.8472219
146P_dedifferentiation_shZFP36L2_4_TACCTCGAGGGAGGGT-1  0.7482630
146P_BASE_shCTRL_GCACATAAGTCGGGAT-1                    1.6116486
146P_HISC_shZFP36L2_4_TTTGACTCAACGCCCA-1               0.6141198
146P_dedifferentiation_shZFP36L2_4_AGCGCCAAGACTCTTG-1  0.9451487
KG146Li_HISC_shZFP36L2_3_CAGGTATCATCCTCAC-1            0.9513942
146Li_dedifferentiation_shZFP36L2_4_AAATGGAAGCGGTAAC-1 1.1316937
146P_BASE_shZFP36L2_3_TCGTGGGAGCTCTTCC-1               0.8669092
146Li_dedifferentiation_shCtrl_TAGACCAAGTAGACCG-1      1.1823075
146P_dedifferentiation_shCtrl_GGGCGTTAGAAGGCTC-1       0.8607233
146P_BASE_shZFP36L2_4_GTCTACCAGGTAGCAC-1               1.7605987
                                                       n_genes_by_counts
146P_HISC_shCTRL_CCGGACACACCACATA-1                    4761
146P_dedifferentiation_shZFP36L2_3_ACTTTGTTCGCTGTTC-1  3471
KG146Li_BASE_shZFP36L2_3_GTGGTTAGTTGGGAAC-1            5775
146P_dedifferentiation_shCtrl_GGGTCTGTCGATGCTA-1       4567
146P_HISC_shZFP36L2_3_TGGAACTCAACCTAAC-1               5019
146Li_dedifferentiation_shZFP36L2_4_TCCCATGAGTGACCTT-1 3116
146P_dedifferentiation_shZFP36L2_3_GGCGTCAGTCCAGCGT-1  2746
146P_BASE_shZFP36L2_3_TCTTTGAGTGCAGGAT-1               2457
146P_dedifferentiation_shZFP36L2_3_CATCAAGTCTCGTGAA-1  4236
146P_BASE_shZFP36L2_3_GTGTGATTCGGAGTAG-1               2752
146P_HISC_shZFP36L2_4_AACACACAGTTTGTCG-1               2088
KG146Li_BASE_shCtrl_ATACCGACAGTAGATA-1                 3873
146P_HISC_shZFP36L2_4_CGAGGAACACTGTTCC-1               4743
146P_BASE_shZFP36L2_3_GGTAATCGTAGTTCCA-1               1014
146P_dedifferentiation_shCtrl_GACCCAGAGTAGAGTT-1       4617
KG146Li_BASE_shZFP36L2_3_TGGGAAGGTCCAGTTA-1            3643
KG146Li_HISC_shCtrl_TCAGTCCCAAGAAACT-1                 3035
146Li_dedifferentiation_shCtrl_GACTATGAGGAGACCT-1      5646
KG146Li_BASE_shZFP36L2_3_TCAGGTAAGACCATAA-1            4597
KG146Li_HISC_shCtrl_TCGAAGTTCTGATTCT-1                 3193
146P_HISC_shZFP36L2_4_CCGGACAAGGCAATGC-1               3904
146P_HISC_shZFP36L2_4_CCTCTCCAGTCGAAGC-1               1005
KG146Li_BASE_shCtrl_CCCTGATAGGGCGAGA-1                 1243
146Li_dedifferentiation_shCtrl_CGATCGGCACAAGTGG-1      3715
146P_HISC_shZFP36L2_3_TCATTTGTCATGCCGG-1               2314
146P_dedifferentiation_shZFP36L2_3_CTCAGGGGTGAGGAAA-1  4544
146P_dedifferentiation_shCtrl_CAGGGCTGTGTTAACC-1       3294
146P_HISC_shZFP36L2_3_TGACGCGAGGCTCAAG-1               4585
KG146Li_HISC_shCtrl_CTACGGGTCACCCTCA-1                 3883
146P_HISC_shZFP36L2_3_GAGGCCTTCACCGCTT-1               4088
⋮                                                      ⋮
KG146Li_BASE_shZFP36L2_3_ACCAAACGTACCGGCT-1            3007
146P_dedifferentiation_shZFP36L2_4_TGATCAGAGCCTATTG-1  3889
146P_HISC_shZFP36L2_4_ACGTTCCCACACAGCC-1                919
146P_BASE_shZFP36L2_3_TCTGTCGGTCAACGCC-1               2058
KG146Li_HISC_shCtrl_TTTCATGAGAGTTGAT-1                 2798
146P_HISC_shZFP36L2_4_CCTTTGGCAGGTGTGA-1               3429
KG146Li_HISC_shZFP36L2_3_GTGTTAGGTTGCGGAA-1            2021
146P_HISC_shZFP36L2_4_TTCCGTGCAAAGAGTT-1               4188
146P_dedifferentiation_shZFP36L2_4_CCACGTTAGACGTCCC-1  2958
146P_HISC_shZFP36L2_3_CTGTCGTAGTGAGGTC-1               4589
146P_HISC_shCTRL_AGTGACTAGTTACGTC-1                     911
146P_dedifferentiation_shCtrl_GATGAGGGTATATGGA-1       2635
146P_BASE_shZFP36L2_4_GTCGTTCGTGCCTTCT-1                924
146P_HISC_shCTRL_ACTATCTGTGATGGCA-1                    1375
146P_HISC_shCTRL_TTGGTTTGTCCCGCAA-1                    1448
146P_dedifferentiation_shZFP36L2_3_CGTTCTGGTCCGGTGT-1  1958
146P_BASE_shZFP36L2_4_TGAGTCAAGCACCAGA-1               6244
146P_dedifferentiation_shZFP36L2_4_CGTAATGTCCCAGGAC-1  4179
146P_BASE_shCTRL_CATGGATAGCACTCGC-1                    1780
KG146Li_BASE_shZFP36L2_3_GACCGTGCATGAGAAT-1            3023
146P_dedifferentiation_shZFP36L2_4_TACCTCGAGGGAGGGT-1  2055
146P_BASE_shCTRL_GCACATAAGTCGGGAT-1                    4073
146P_HISC_shZFP36L2_4_TTTGACTCAACGCCCA-1               1948
146P_dedifferentiation_shZFP36L2_4_AGCGCCAAGACTCTTG-1  2990
KG146Li_HISC_shZFP36L2_3_CAGGTATCATCCTCAC-1            2191
146Li_dedifferentiation_shZFP36L2_4_AAATGGAAGCGGTAAC-1 3917
146P_BASE_shZFP36L2_3_TCGTGGGAGCTCTTCC-1               2184
146Li_dedifferentiation_shCtrl_TAGACCAAGTAGACCG-1      3695
146P_dedifferentiation_shCtrl_GGGCGTTAGAAGGCTC-1       2583
146P_BASE_shZFP36L2_4_GTCTACCAGGTAGCAC-1               5343

In [20]:
# Define the column data
coldata <- adata$obs[,c("Tumor_Site","Culture_Media", "ZFP_Expression")]

# Convert column data to factors
coldata$Tumor_Site <- factor(coldata$Tumor_Site)
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)

# Design a DESeqDataSet
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + ZFP_Expression
)

converting counts to integer mode

In [21]:
# Add a pseudo-count of 1 to all counts
count_matrix <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata$raw$var_names

# Set the reference levels
coldata$Tumor_Site<-relevel(coldata$Tumor_Site,ref="Primary")
coldata$Culture_Media<-relevel(coldata$Culture_Media,ref="BASE")
coldata$ZFP_Expression<-relevel(coldata$ZFP_Expression,ref="CTRL")

# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Tumor_Site + Culture_Media + ZFP_Expression 
)

converting counts to integer mode

In [ ]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

estimating size factors

estimating dispersions

gene-wise dispersion estimates

In [ ]:
# Specify the date
date <- '020224'

# Specify the directory path
directory_path <- paste("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output_new/deseq/deseq.", date, sep="")

# Check if the directory exists, and create it if not
if (!dir.exists(directory_path)) {
  dir.create(directory_path, recursive = TRUE)
}

# Specify the file path where you want to save the results
result_file <- paste(directory_path, "/sc_zfpexp_results.csv", sep="")

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = paste(directory_path, "/sc_zfpexp_dds.rds", sep=""))

# Save the DESeq results
saveRDS(results(dds_1), file = paste(directory_path, "/sc_zfpexp_results.rds", sep=""))

### DEGs for Primary Tumor

In [4]:
# Read in the adata for primary tumor site
adata_primary = sc$read_h5ad('/data/chanjlab/CRC_ZFP36L2.092023/Organoid/input/degs/primary_tumor.h5ad')

In [5]:
adata_primary

AnnData object with n_obs × n_vars = 30895 × 31586
    obs: 'background_fraction', 'cell_probability', 'cell_size', 'droplet_efficiency', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'log10GenesPerUMI', 'original_total_counts', 'log10_original_total_counts', 'mito_frac', 'Patient', 'Tumor_Site', 'Culture_Media', 'ZFP_Expression', 'Replicate', 'Batch', 'Sample', 'phenograph', 'leiden'
    var: 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'ribo', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'diffmap_evals', 'hvg', 'leiden', 'log1p', 'neighbors', 'num_components', 'paga', 'phenograph_sizes', 'rank_genes_groups', 'umap', 'var_explained'
    obsm: 'X_diffmap', 'X_pca', 'X_umap', 'gene_expression_encoding'
    layers: 'without_log'
    obsp: 'connectivities', 'distances'

In [6]:
# Get the counts matrix
counts = as.matrix(adata_primary$X)

# Normalize
ms <- rowSums(counts)
norm_df <- counts/ms * median(ms)

# Log transform
counts <- log(norm_df + 1)

# Add pseudocount
counts <- counts + 1

# Round since error that not all values are integers
counts <- round(counts)

# Transpose
counts <- t(counts)

# Assign row and column names to the counts matrix
rownames(counts) <- adata_primary$var_names
colnames(counts) <- adata_primary$obs_names

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 7.3 GiB”

In [55]:
# Extract count matrix from the raw layer
count_matrix <- as.matrix(adata_primary$X)
# Transpose the ocunt matrix
count_matrix <- t(count_matrix)
count_matrix <- round(count_matrix)
# Add a pseudocount
count_matrix <- count_matrix + 1 
# Normalize the count matrix by library size
library_sizes <- colSums(count_matrix)
count_matrix <- count_matrix / library_sizes * mean(library_sizes)

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 7.3 GiB”

In [7]:
counts

            146P_dedifferentiation_shCtrl_CTCTCAGAGGTAGACC-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        2
AARS2       1
AARSD1      2
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_HISC_shZFP36L2_4_GTGCAGCAGAGAGGGC-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       2
AAGAB       2
AAK1        1
AAMDC       2
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        2
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       2
            146P_BASE_shZFP36L2_3_TAGAGTCAGAAAGTCT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       2
AARSD1      2
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      2
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      2
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_BASE_shCTRL_GGGTCACGTGATACTC-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      2
ZSWIM7      2
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       2
            146P_BASE_shCTRL_GGAGATGAGTTCCAGT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        2
AAMDC       1
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      2
ZSWIM5      1
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       1
            146P_BASE_shZFP36L2_4_GAGTTTGCAAGACGGT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      2
AASDH       2
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        2
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_BASE_shZFP36L2_3_CTAACCCTCACATCAG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        2
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       1
            146P_HISC_shCTRL_TGCAGATAGTCTACCA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_dedifferentiation_shZFP36L2_3_CACTTCGCATGTGGTT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        2
AARS2       1
AARSD1      1
AASDH       2
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_HISC_shCTRL_AAGAACAAGGACACTG-1 ⋯
A1BG        1                                   ⋯
A1BG-AS1    1                                   ⋯
A1CF        1                                   ⋯
A2M         1                                   ⋯
A2M-AS1     1                                   ⋯
A2ML1       1                                   ⋯
A2ML1-AS1   1                                   ⋯
A2ML1-AS2   1                                   ⋯
A3GALT2     1                                   ⋯
A4GALT      1                                   ⋯
A4GNT       1                                   ⋯
AAAS        1                                   ⋯
AACS        1                                   ⋯
AADAC       1                                   ⋯
AADACL2     1                                   ⋯
AADACL2-AS1 1                                   ⋯
AADACL3     1                                   ⋯
AADACL4     1                                   ⋯
AADAT       1                                   ⋯
AAGAB       1                                   ⋯
AAK1        1                                   ⋯
AAMDC       1                                   ⋯
AAMP        1                                   ⋯
AANAT       1                                   ⋯
AAR2        1                                   ⋯
AARD        1                                   ⋯
AARS        1                                   ⋯
AARS2       1                                   ⋯
AARSD1      1                                   ⋯
AASDH       1                                   ⋯
⋮           ⋮                                   ⋱
ZSCAN26     1                                   ⋯
ZSCAN29     1                                   ⋯
ZSCAN30     1                                   ⋯
ZSCAN31     1                                   ⋯
ZSCAN32     1                                   ⋯
ZSCAN4      1                                   ⋯
ZSCAN5A     1                                   ⋯
ZSCAN5B     1                                   ⋯
ZSCAN9      1                                   ⋯
ZSWIM1      1                                   ⋯
ZSWIM2      1                                   ⋯
ZSWIM3      1                                   ⋯
ZSWIM4      1                                   ⋯
ZSWIM5      1                                   ⋯
ZSWIM6      2                                   ⋯
ZSWIM7      2                                   ⋯
ZSWIM8      1                                   ⋯
ZSWIM8-AS1  1                                   ⋯
ZSWIM9      1                                   ⋯
ZUP1        1                                   ⋯
ZW10        1                                   ⋯
ZWILCH      1                                   ⋯
ZWINT       2                                   ⋯
ZXDA        1                                   ⋯
ZXDB        1                                   ⋯
ZXDC        1                                   ⋯
ZYG11A      1                                   ⋯
ZYG11B      1                                   ⋯
ZYX         1                                   ⋯
ZZEF1       1                                   ⋯
            146P_dedifferentiation_shZFP36L2_4_TACCTCGTCGACTCCT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        2
AARD        1
AARS        1
AARS2       1
AARSD1      2
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     2
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        2
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_BASE_shZFP36L2_4_AGGACGATCTCTCTTC-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        2
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        2
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       2
            146P_dedifferentiation_shCtrl_AAGACTCGTGATATAG-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        2
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       2
AAGAB       2
AAK1        2
AAMDC       1
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      2
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       2
            146P_HISC_shZFP36L2_4_CCTCCTCCATATGGCT-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        2
AACS        2
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      2
ZSWIM5      2
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      2
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_HISC_shZFP36L2_4_ATGTCTTCAGTCCCGA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       2
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      2
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      2
ZYX         1
ZZEF1       1
            146P_BASE_shCTRL_CCTCAGTCAGGTATGG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        2
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        2
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_HISC_shCTRL_CCTCACAGTTGGTGTT-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        2
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       2
AAK1        1
AAMDC       1
AAMP        2
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      2
AASDH       2
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      1
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      2
ZWINT       2
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_BASE_shZFP36L2_3_TCACGCTTCATAGGCT-1
A1BG        1
A1BG-AS1    1
A1CF        2
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        2
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       2
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     2
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      2
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        1
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       1
            146P_dedifferentiation_shZFP36L2_4_TCGGGTGCAAACGGCA-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       1
AAK1        1
AAMDC       1
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        2
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1
ZSCAN32     1
ZSCAN4      1
ZSCAN5A     1
ZSCAN5B     1
ZSCAN9      1
ZSWIM1      1
ZSWIM2      1
ZSWIM3      1
ZSWIM4      1
ZSWIM5      2
ZSWIM6      1
ZSWIM7      1
ZSWIM8      1
ZSWIM8-AS1  1
ZSWIM9      1
ZUP1        1
ZW10        1
ZWILCH      1
ZWINT       1
ZXDA        1
ZXDB        1
ZXDC        2
ZYG11A      1
ZYG11B      1
ZYX         1
ZZEF1       2
            146P_BASE_shZFP36L2_4_ACTGCAATCAGTGTTG-1
A1BG        1
A1BG-AS1    1
A1CF        1
A2M         1
A2M-AS1     1
A2ML1       1
A2ML1-AS1   1
A2ML1-AS2   1
A3GALT2     1
A4GALT      1
A4GNT       1
AAAS        1
AACS        1
AADAC       1
AADACL2     1
AADACL2-AS1 1
AADACL3     1
AADACL4     1
AADAT       1
AAGAB       2
AAK1        1
AAMDC       2
AAMP        1
AANAT       1
AAR2        1
AARD        1
AARS        1
AARS2       1
AARSD1      1
AASDH       1
⋮           ⋮
ZSCAN26     1
ZSCAN29     1
ZSCAN30     1
ZSCAN31     1

In [ ]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = counts,
  colData = coldata,
  design = ~ Culture_Media + ZFP_Expression 
)

In [8]:
# Define the column data
coldata <- adata_primary$obs[,c("Culture_Media", "ZFP_Expression")]

# Convert column data to factors
coldata$Culture_Media <- factor(coldata$Culture_Media)
coldata$ZFP_Expression <- factor(coldata$ZFP_Expression)

# Set the reference levels
coldata$Culture_Media<-relevel(coldata$Culture_Media,ref="BASE")
coldata$ZFP_Expression<-relevel(coldata$ZFP_Expression,ref="CTRL")

In [ ]:
# Add a pseudo-count of 1 to all counts
counts <- counts(dds_1) + 1

# Specify the row names as the gene names
rownames(count_matrix) <- adata_primary$var_names

# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = coldata,
  design = ~ Culture_Media + ZFP_Expression:Culture_Media 
)

In [ ]:
# Design a DESeqDataSet with modified count matrix
dds_1 <- DESeqDataSetFromMatrix(
  countData = counts,
  colData = coldata
)

In [25]:
# Filter the DDS object
keep <- rowSums(counts(dds_1)) >= 10
dds_1 <- dds_1[keep,]

In [13]:
dds_1 <- estimateSizeFactors(dds_1)

In [15]:
dds_1 <- estimateDispersionsGeneEst(dds_1)

In [16]:
dispersions(dds_1) <- mcols(dds_1)$dispGeneEst

In [17]:
dds_1 <- nbinomWaldTest(dds_1)

In [21]:
dds_1$group <- factor(paste0(dds_1$Culture_Media, dds_1$ZFP_Expression))

In [23]:
dds_1$group

    [1] DedifferentiatedCTRL   HISCZFP_KD             BASEZFP_KD
    [4] BASECTRL               BASECTRL               BASEZFP_KD
    [7] BASEZFP_KD             HISCCTRL               DedifferentiatedZFP_KD
   [10] HISCCTRL               HISCCTRL               BASEZFP_KD
   [13] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
   [16] DedifferentiatedZFP_KD BASEZFP_KD             HISCCTRL
   [19] DedifferentiatedZFP_KD BASECTRL               DedifferentiatedZFP_KD
   [22] DedifferentiatedZFP_KD HISCZFP_KD             BASEZFP_KD
   [25] DedifferentiatedZFP_KD BASEZFP_KD             BASECTRL
   [28] BASECTRL               BASEZFP_KD             BASEZFP_KD
   [31] BASECTRL               DedifferentiatedCTRL   BASEZFP_KD
   [34] BASECTRL               DedifferentiatedCTRL   HISCZFP_KD
   [37] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedZFP_KD
   [40] DedifferentiatedZFP_KD BASEZFP_KD             DedifferentiatedZFP_KD
   [43] BASEZFP_KD             HISCCTRL               HISCZFP_KD
   [46] DedifferentiatedZFP_KD BASECTRL               BASECTRL
   [49] DedifferentiatedCTRL   HISCCTRL               HISCZFP_KD
   [52] BASEZFP_KD             HISCZFP_KD             DedifferentiatedCTRL
   [55] DedifferentiatedCTRL   BASECTRL               HISCZFP_KD
   [58] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
   [61] DedifferentiatedZFP_KD BASECTRL               BASEZFP_KD
   [64] DedifferentiatedCTRL   HISCCTRL               HISCZFP_KD
   [67] DedifferentiatedCTRL   BASECTRL               DedifferentiatedZFP_KD
   [70] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
   [73] HISCZFP_KD             BASEZFP_KD             BASECTRL
   [76] HISCZFP_KD             DedifferentiatedCTRL   BASEZFP_KD
   [79] BASEZFP_KD             HISCCTRL               HISCCTRL
   [82] BASEZFP_KD             HISCZFP_KD             BASEZFP_KD
   [85] HISCZFP_KD             BASECTRL               BASECTRL
   [88] BASECTRL               BASEZFP_KD             BASEZFP_KD
   [91] HISCCTRL               BASEZFP_KD             HISCCTRL
   [94] DedifferentiatedZFP_KD BASECTRL               BASEZFP_KD
   [97] DedifferentiatedZFP_KD BASECTRL               HISCZFP_KD
  [100] DedifferentiatedCTRL   HISCZFP_KD             DedifferentiatedCTRL
  [103] HISCZFP_KD             BASECTRL               BASEZFP_KD
  [106] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [109] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [112] HISCCTRL               DedifferentiatedZFP_KD HISCCTRL
  [115] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedZFP_KD
  [118] HISCZFP_KD             DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [121] DedifferentiatedZFP_KD BASEZFP_KD             DedifferentiatedZFP_KD
  [124] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [127] BASEZFP_KD             HISCZFP_KD             DedifferentiatedZFP_KD
  [130] DedifferentiatedZFP_KD BASECTRL               DedifferentiatedZFP_KD
  [133] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [136] BASECTRL               BASEZFP_KD             DedifferentiatedZFP_KD
  [139] HISCZFP_KD             HISCZFP_KD             DedifferentiatedCTRL
  [142] HISCCTRL               BASECTRL               DedifferentiatedZFP_KD
  [145] DedifferentiatedZFP_KD DedifferentiatedCTRL   HISCZFP_KD
  [148] BASECTRL               BASEZFP_KD             HISCCTRL
  [151] DedifferentiatedCTRL   HISCZFP_KD             DedifferentiatedCTRL
  [154] DedifferentiatedZFP_KD BASECTRL               DedifferentiatedZFP_KD
  [157] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [160] HISCZFP_KD             HISCCTRL               BASECTRL
  [163] BASEZFP_KD             BASECTRL               BASEZFP_KD
  [166] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [169] HISCCTRL               HISCCTRL               BASECTRL
  [172] HISCZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [175] DedifferentiatedZFP_KD DedifferentiatedZFP_KD BASEZFP_KD
  [178] BASECTRL               DedifferentiatedCTRL   BASEZFP_KD
  [181] DedifferentiatedZFP_KD HISCZFP_KD             HISCCTRL
  [184] BASEZFP_KD             BASEZFP_KD             HISCCTRL
  [187] BASECTRL               HISCZFP_KD             DedifferentiatedZFP_KD
  [190] HISCCTRL               DedifferentiatedCTRL   BASEZFP_KD
  [193] BASECTRL               HISCZFP_KD             BASEZFP_KD
  [196] HISCZFP_KD             DedifferentiatedZFP_KD HISCCTRL
  [199] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [202] DedifferentiatedCTRL   DedifferentiatedZFP_KD DedifferentiatedCTRL
  [205] HISCCTRL               DedifferentiatedZFP_KD BASEZFP_KD
  [208] DedifferentiatedZFP_KD DedifferentiatedZFP_KD HISCZFP_KD
  [211] BASECTRL               BASEZFP_KD             DedifferentiatedCTRL
  [214] BASEZFP_KD             HISCZFP_KD             BASECTRL
  [217] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [220] DedifferentiatedZFP_KD BASEZFP_KD             HISCZFP_KD
  [223] DedifferentiatedZFP_KD DedifferentiatedCTRL   BASECTRL
  [226] DedifferentiatedCTRL   DedifferentiatedZFP_KD DedifferentiatedCTRL
  [229] DedifferentiatedZFP_KD HISCZFP_KD             BASEZFP_KD
  [232] HISCZFP_KD             HISCZFP_KD             HISCZFP_KD
  [235] DedifferentiatedZFP_KD HISCZFP_KD             BASECTRL
  [238] BASEZFP_KD             HISCZFP_KD             HISCZFP_KD
  [241] BASECTRL               BASEZFP_KD             HISCZFP_KD
  [244] HISCZFP_KD             HISCCTRL               HISCZFP_KD
  [247] HISCZFP_KD             BASECTRL               DedifferentiatedZFP_KD
  [250] BASEZFP_KD             HISCZFP_KD             DedifferentiatedZFP_KD
  [253] HISCCTRL               BASEZFP_KD             BASEZFP_KD
  [256] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [259] HISCCTRL               HISCZFP_KD             BASEZFP_KD
  [262] BASECTRL               HISCCTRL               HISCZFP_KD
  [265] DedifferentiatedZFP_KD BASECTRL               BASECTRL
  [268] HISCCTRL               BASECTRL               HISCCTRL
  [271] HISCZFP_KD             BASEZFP_KD             BASEZFP_KD
  [274] BASECTRL               BASEZFP_KD             BASEZFP_KD
  [277] HISCCTRL               BASECTRL               DedifferentiatedCTRL
  [280] HISCZFP_KD             DedifferentiatedZFP_KD BASECTRL
  [283] DedifferentiatedZFP_KD DedifferentiatedZFP_KD HISCZFP_KD
  [286] BASEZFP_KD             DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [289] DedifferentiatedCTRL   BASEZFP_KD             HISCCTRL
  [292] BASEZFP_KD             HISCZFP_KD             DedifferentiatedZFP_KD
  [295] HISCCTRL               HISCCTRL               DedifferentiatedCTRL
  [298] BASECTRL               DedifferentiatedZFP_KD BASECTRL
  [301] HISCZFP_KD             BASEZFP_KD             HISCZFP_KD
  [304] BASEZFP_KD             BASEZFP_KD             HISCZFP_KD
  [307] DedifferentiatedZFP_KD HISCZFP_KD             HISCCTRL
  [310] HISCZFP_KD             BASEZFP_KD             HISCZFP_KD
  [313] DedifferentiatedZFP_KD HISCZFP_KD             BASEZFP_KD
  [316] HISCZFP_KD             HISCZFP_KD             BASEZFP_KD
  [319] DedifferentiatedZFP_KD HISCCTRL               HISCCTRL
  [322] BASEZFP_KD             BASEZFP_KD             BASEZFP_KD
  [325] BASEZFP_KD             BASECTRL               HISCZFP_KD
  [328] BASECTRL               HISCCTRL               DedifferentiatedZFP_KD
  [331] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [334] HISCZFP_KD             BASECTRL               BASECTRL
  [337] DedifferentiatedZFP_KD BASEZFP_KD             BASECTRL
  [340] DedifferentiatedZFP_KD DedifferentiatedCTRL   BASECTRL
  [343] BASEZFP_KD             HISCZFP_KD             DedifferentiatedCTRL
  [346] HISCZFP_KD             DedifferentiatedZFP_KD BASECTRL
  [349] DedifferentiatedCTRL   DedifferentiatedZFP_KD BASEZFP_KD
  [352] HISCZFP_KD             BASECTRL               HISCZFP_KD
  [355] DedifferentiatedZFP_KD BASEZFP_KD             DedifferentiatedCTRL
  [358] BASEZFP_KD             HISCZFP_KD             BASEZFP_KD
  [361] HISCZFP_KD             BASEZFP_KD             BASEZFP_KD
  [364] HISCZFP_KD             BASECTRL               DedifferentiatedZFP_KD
  [367] BASECTRL               DedifferentiatedZFP_KD HISCCTRL
  [370] HISCZFP_KD             HISCZFP_KD             HISCZFP_KD
  [373] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [376] BASEZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [379] HISCZFP_KD             DedifferentiatedCTRL   BASECTRL
  [382] HISCCTRL               HISCCTRL               HISCZFP_KD
  [385] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedZFP_KD
  [388] HISCZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [391] HISCZFP_KD             DedifferentiatedZFP_KD BASECTRL
  [394] HISCZFP_KD             HISCCTRL               DedifferentiatedZFP_KD
  [397] BASEZFP_KD             HISCCTRL               BASEZFP_KD
  [400] BASEZFP_KD             DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [403] HISCZFP_KD             HISCCTRL               BASECTRL
  [406] HISCZFP_KD             DedifferentiatedCTRL   BASEZFP_KD
  [409] BASEZFP_KD             HISCZFP_KD             HISCZFP_KD
  [412] BASEZFP_KD             HISCCTRL               DedifferentiatedZFP_KD
  [415] BASEZFP_KD             BASEZFP_KD             DedifferentiatedCTRL
  [418] BASEZFP_KD             BASECTRL               HISCZFP_KD
  [421] HISCCTRL               HISCCTRL               HISCCTRL
  [424] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [427] DedifferentiatedZFP_KD DedifferentiatedZFP_KD BASECTRL
  [430] BASEZFP_KD             HISCZFP_KD             DedifferentiatedZFP_KD
  [433] HISCZFP_KD             DedifferentiatedCTRL   HISCZFP_KD
  [436] HISCZFP_KD             HISCZFP_KD             DedifferentiatedZFP_KD
  [439] HISCCTRL               DedifferentiatedCTRL   HISCZFP_KD
  [442] HISCZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [445] DedifferentiatedZFP_KD HISCCTRL               HISCCTRL
  [448] BASEZFP_KD             BASEZFP_KD             DedifferentiatedCTRL
  [451] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [454] DedifferentiatedCTRL   HISCCTRL               BASEZFP_KD
  [457] DedifferentiatedCTRL   HISCZFP_KD             BASECTRL
  [460] BASEZFP_KD             HISCCTRL               BASECTRL
  [463] HISCZFP_KD             BASEZFP_KD             BASECTRL
  [466] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedZFP_KD
  [469] BASEZFP_KD             BASEZFP_KD             DedifferentiatedCTRL
  [472] HISCCTRL               HISCZFP_KD             HISCZFP_KD
  [475] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [478] DedifferentiatedCTRL   BASECTRL               BASECTRL
  [481] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [484] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [487] BASEZFP_KD             HISCZFP_KD             HISCZFP_KD
  [490] BASECTRL               HISCZFP_KD             BASEZFP_KD
  [493] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [496] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [499] DedifferentiatedZFP_KD HISCCTRL               DedifferentiatedCTRL
  [502] HISCZFP_KD             HISCCTRL               HISCZFP_KD
  [505] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedZFP_KD
  [508] DedifferentiatedCTRL   DedifferentiatedZFP_KD BASEZFP_KD
  [511] DedifferentiatedZFP_KD BASEZFP_KD             BASECTRL
  [514] DedifferentiatedZFP_KD HISCZFP_KD             HISCCTRL
  [517] BASEZFP_KD             DedifferentiatedZFP_KD DedifferentiatedCTRL
  [520] DedifferentiatedCTRL   DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [523] DedifferentiatedZFP_KD HISCZFP_KD             HISCCTRL
  [526] BASEZFP_KD             BASEZFP_KD             BASEZFP_KD
  [529] BASECTRL               BASECTRL               DedifferentiatedZFP_KD
  [532] BASEZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [535] BASEZFP_KD             BASECTRL               BASEZFP_KD
  [538] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedCTRL
  [541] BASEZFP_KD             BASEZFP_KD             BASEZFP_KD
  [544] HISCZFP_KD             DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [547] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [550] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [553] BASEZFP_KD             HISCZFP_KD             DedifferentiatedCTRL
  [556] HISCZFP_KD             BASEZFP_KD             BASECTRL
  [559] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedCTRL
  [562] BASEZFP_KD             HISCCTRL               HISCZFP_KD
  [565] BASEZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [568] BASECTRL               HISCZFP_KD             DedifferentiatedZFP_KD
  [571] BASEZFP_KD             BASEZFP_KD             DedifferentiatedCTRL
  [574] DedifferentiatedZFP_KD DedifferentiatedCTRL   BASEZFP_KD
  [577] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [580] DedifferentiatedZFP_KD HISCCTRL               HISCZFP_KD
  [583] BASECTRL               DedifferentiatedZFP_KD DedifferentiatedZFP_KD
  [586] DedifferentiatedZFP_KD BASEZFP_KD             HISCZFP_KD
  [589] HISCCTRL               DedifferentiatedZFP_KD HISCCTRL
  [592] BASEZFP_KD             BASECTRL               BASEZFP_KD
  [595] HISCCTRL               HISCZFP_KD             BASEZFP_KD
  [598] BASEZFP_KD             BASECTRL               BASEZFP_KD
  [601] HISCCTRL               BASECTRL               DedifferentiatedCTRL
  [604] HISCZFP_KD             HISCZFP_KD             DedifferentiatedZFP_KD
  [607] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [610] DedifferentiatedZFP_KD BASEZFP_KD             BASEZFP_KD
  [613] DedifferentiatedCTRL   DedifferentiatedZFP_KD HISCZFP_KD
  [616] BASECTRL               BASECTRL               DedifferentiatedCTRL
  [619] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [622] HISCZFP_KD             HISCZFP_KD             DedifferentiatedCTRL
  [625] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [628] BASECTRL               HISCCTRL               BASEZFP_KD
  [631] DedifferentiatedCTRL   BASECTRL               BASEZFP_KD
  [634] BASECTRL               HISCCTRL               HISCZFP_KD
  [637] DedifferentiatedZFP_KD BASECTRL               DedifferentiatedZFP_KD
  [640] BASECTRL               BASEZFP_KD             DedifferentiatedCTRL
  [643] HISCZFP_KD             HISCCTRL               DedifferentiatedZFP_KD
  [646] BASECTRL               BASECTRL               HISCZFP_KD
  [649] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [652] BASEZFP_KD             BASEZFP_KD             DedifferentiatedCTRL
  [655] DedifferentiatedZFP_KD DedifferentiatedZFP_KD HISCZFP_KD
  [658] HISCZFP_KD             DedifferentiatedCTRL   DedifferentiatedZFP_KD
  [661] DedifferentiatedZFP_KD HISCZFP_KD             DedifferentiatedZFP_KD
  [664] BASECTRL               BASEZFP_KD             DedifferentiatedZFP_KD
  [667] BASEZFP_KD             DedifferentiatedCTRL   HISCCTRL
  [670] DedifferentiatedZFP_KD BASEZFP_KD             DedifferentiatedZFP_KD
  [673] BASECTRL               HISCCTRL               HISCZFP_KD
  [676] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [679] DedifferentiatedCTRL   BASEZFP_KD             BASEZFP_KD
  [682] BASEZFP_KD             BASECTRL               BASEZFP_KD
  [685] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [688] DedifferentiatedZFP_KD BASEZFP_KD             BASEZFP_KD
  [691] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [694] DedifferentiatedCTRL   BASEZFP_KD             BASECTRL
  [697] DedifferentiatedZFP_KD HISCCTRL               DedifferentiatedZFP_KD
  [700] HISCZFP_KD             DedifferentiatedCTRL   BASEZFP_KD
  [703] DedifferentiatedZFP_KD HISCCTRL               DedifferentiatedCTRL
  [706] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [709] DedifferentiatedZFP_KD DedifferentiatedCTRL   DedifferentiatedZFP_KD
  [712] BASECTRL               HISCZFP_KD             DedifferentiatedZFP_KD
  [715] BASEZFP_KD             DedifferentiatedZFP_KD HISCZFP_KD
  [718] HISCCTRL               BASEZFP_KD             BASECTRL
  [721] BASEZFP_KD             BASEZFP_KD             BASEZFP_KD
  [724] HISCCTRL               BASECTRL               BASEZFP_KD
  [727] BASEZFP_KD             BASEZFP_KD             BASEZFP_KD
  [730] BASECTRL               DedifferentiatedZFP_KD BASEZFP_KD
  [733] DedifferentiatedCTRL   HISCZFP_KD             HISCZFP_KD
  [736] BASECTRL               BASEZFP_KD             BASEZFP_KD
  [739] BASEZFP_KD             BASECTRL               HISCZFP_KD
  [742] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedCTRL
  [745] HISCZFP_KD             BASEZFP_KD             BASECTRL
  [748] DedifferentiatedZFP_KD DedifferentiatedCTRL   DedifferentiatedZFP_KD
  [751] BASEZFP_KD             DedifferentiatedZFP_KD HISCCTRL
  [754] DedifferentiatedZFP_KD HISCCTRL               BASEZFP_KD
  [757] HISCCTRL               BASECTRL               BASEZFP_KD
  [760] HISCZFP_KD             BASECTRL               DedifferentiatedZFP_KD
  [763] BASEZFP_KD             BASEZFP_KD             HISCZFP_KD
  [766] BASECTRL               DedifferentiatedZFP_KD HISCZFP_KD
  [769] BASEZFP_KD             BASECTRL               DedifferentiatedZFP_KD
  [772] DedifferentiatedZFP_KD HISCCTRL               DedifferentiatedZFP_KD
  [775] HISCZFP_KD             DedifferentiatedZFP_KD DedifferentiatedCTRL
  [778] DedifferentiatedCTRL   HISCZFP_KD             HISCCTRL
  [781] HISCCTRL               BASEZFP_KD             BASEZFP_KD
  [784] BASEZFP_KD             BASECTRL               DedifferentiatedCTRL
  [787] DedifferentiatedCTRL   DedifferentiatedZFP_KD HISCZFP_KD
  [790] HISCCTRL               DedifferentiatedZFP_KD HISCZFP_KD
  [793] BASECTRL               HISCCTRL               BASECTRL
  [796] DedifferentiatedZFP_KD HISCCTRL               DedifferentiatedZFP_KD
  [799] BASEZFP_KD             DedifferentiatedCTRL   BASEZFP_KD
  [802] BASEZFP_KD             HISCZFP_KD             BASEZFP_KD
  [805] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedCTRL
  [808] BASEZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [811] DedifferentiatedZFP_KD DedifferentiatedCTRL   BASECTRL
  [814] BASEZFP_KD             HISCZFP_KD             HISCCTRL
  [817] HISCZFP_KD             BASEZFP_KD             DedifferentiatedZFP_KD
  [820] BASEZFP_KD             HISCCTRL               BASECTRL
  [823] DedifferentiatedZFP_KD DedifferentiatedZFP_KD BASEZFP_KD
  [826] DedifferentiatedZFP_KD DedifferentiatedCTRL   HISCCTRL
  [829] BASECTRL               BASEZFP_KD             BASECTRL
  [832] DedifferentiatedCTRL   BASEZFP_KD             HISCCTRL
  [835] BASEZFP_KD             DedifferentiatedCTRL   HISCZFP_KD
  [838] DedifferentiatedZFP_KD HISCZFP_KD             HISCZFP_KD
  [841] HISCZFP_KD             BASECTRL               DedifferentiatedZFP_KD
  [844] BASEZFP_KD             BASECTRL               HISCCTRL
  [847] DedifferentiatedCTRL   HISCZFP_KD             HISCCTRL
  [850] HISCZFP_KD             BASEZFP_KD             HISCZFP_KD
  [853] DedifferentiatedZFP_KD HISCCTRL               HISCCTRL
  [856] HISCZFP_KD             BASEZFP_KD             BASEZFP_KD
  [859] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [862] DedifferentiatedZFP_KD BASEZFP_KD             BASEZFP_KD
  [865] HISCZFP_KD             DedifferentiatedZFP_KD BASEZFP_KD
  [868] DedifferentiatedCTRL   BASECTRL               BASEZFP_KD
  [871] DedifferentiatedZFP_KD DedifferentiatedZFP_KD HISCZFP_KD
  [874] DedifferentiatedZFP_KD DedifferentiatedZFP_KD DedifferentiatedZFP_KD

In [19]:
# Perform DESeq analysis
dds_1 <- DESeq(dds_1)

# Extract results
result_names_1 <- resultsNames(dds_1)
result_names_1

# Specify the contrast and extract results
res_1 <- results(dds_1)
res_1

using pre-existing size factors

estimating dispersions

found already estimated dispersions, replacing these

gene-wise dispersion estimates

In [ ]:
# Specify the date
date <- '020224'

# Specify the directory path
directory_path <- paste("/data/chanjlab/CRC_ZFP36L2.092023/Organoid/output_new/deseq/deseq.", date, sep="")

# Check if the directory exists, and create it if not
if (!dir.exists(directory_path)) {
  dir.create(directory_path, recursive = TRUE)
}

# Specify the file path where you want to save the results
result_file <- paste(directory_path, "/sc_zfpexp_results.csv", sep="")

# Write the results table to a CSV file
write.csv(as.data.frame(res_1), file = result_file)

# Save the DESeqDataSet object
saveRDS(dds_1, file = paste(directory_path, "/sc_zfpexp_dds.rds", sep=""))

# Save the DESeq results
saveRDS(results(dds_1), file = paste(directory_path, "/sc_zfpexp_results.rds", sep=""))